/* Generated by           cobc 3.2.0 */
/* Generated from         customer.cob */
/* Generated at           set 13 2023 12:16:59 */
/* GnuCOBOL build date    Jul 28 2023 19:10:09 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -g -fsource-location -ftraceall -Q --coverage -A --coverage -v -O0 -x customer.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"customer.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"set 13 2023 12:16:59"
#define  COB_MODULE_DATE		20230913
#define  COB_MODULE_TIME		121659

/* Global variables */
#include "customer.c.h"

/* Function prototypes */

static int		CUSTOMERS ();
static int		CUSTOMERS_ (const int);
static void		CUSTOMERS_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (CUSTOMERS ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'CUSTOMERS' */

/* ENTRY 'CUSTOMERS' */

static int
CUSTOMERS ()
{
  return CUSTOMERS_ (0);
}

static int
CUSTOMERS_ (const int entry)
{
  /* Program local variables */
  #include "customer.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 103       : Entry     CUSTOMERS               : customer.cob */
  l_2:;
#line 103 "customer.cob"
  ENTRY_CUSTOMERS:	module->statement = STMT_ENTRY;
#line 105 "customer.c"
  module->module_stmt = 0x00100067;
  cob_trace_entry (st_1);
  module->section_name = NULL;
  module->paragraph_name = NULL;
  cob_trace_sect (NULL);

  /* Line: 103       : Paragraph 001-START               : customer.cob */
#line 103 "customer.cob"
  PARAGRAPH_001__START_l_4:	module->statement = STMT_ENTRY;
#line 115 "customer.c"
  module->paragraph_name = st_2;
  cob_trace_para (st_2);

  /* Line: 104       : SET                : customer.cob */
#line 104 "customer.cob"
  module->statement = STMT_SET;
#line 122 "customer.c"
  module->module_stmt = 0x00100068;
  cob_trace_statement (STMT_SET);
  cob_set_environment ((cob_field *)&c_1, (cob_field *)&c_2);

  /* Line: 105       : SET                : customer.cob */
#line 105 "customer.cob"
  module->statement = STMT_SET;
#line 130 "customer.c"
  module->module_stmt = 0x00100069;
  cob_trace_statement (STMT_SET);
  cob_set_environment ((cob_field *)&c_3, (cob_field *)&c_2);

  /* Line: 106       : SET                : customer.cob */
#line 106 "customer.cob"
  module->statement = STMT_SET;
#line 138 "customer.c"
  module->module_stmt = 0x0010006A;
  cob_trace_statement (STMT_SET);
  cob_set_environment ((cob_field *)&c_4, (cob_field *)&c_5);

  /* Line: 109       : ACCEPT             : customer.cob */
#line 109 "customer.cob"
  module->statement = STMT_ACCEPT;
#line 146 "customer.c"
  module->module_stmt = 0x0010006D;
  cob_trace_statement (STMT_ACCEPT);
  cob_screen_line_col (&f_39, 0);

  /* Line: 110       : ACCEPT             : customer.cob */
#line 110 "customer.cob"
  module->statement = STMT_ACCEPT;
#line 154 "customer.c"
  module->module_stmt = 0x0010006E;
  cob_trace_statement (STMT_ACCEPT);
  cob_screen_line_col (&f_40, 1);

  /* Line: 111       : PERFORM            : customer.cob */
#line 111 "customer.cob"
  module->statement = STMT_PERFORM;
#line 162 "customer.c"
  module->module_stmt = 0x0010006F;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM 007-OPEN-FILES */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 20;
  frame_ptr->return_address_ptr = &&l_22;
  goto l_20;
  l_22:
  frame_ptr--;

  /* Line: 112       : PERFORM            : customer.cob */
#line 112 "customer.cob"
  module->statement = STMT_PERFORM;
#line 178 "customer.c"
  module->module_stmt = 0x00100070;
  cob_trace_statement (STMT_PERFORM);
  for (;;)
  {
    /* Line: 112       : UNTIL              : customer.cob */
#line 112 "customer.cob"
    module->statement = STMT_UNTIL;
#line 186 "customer.c"
    module->module_stmt = 0x00100070;
    cob_trace_statement (STMT_UNTIL);
    if ((((int)(int)(*(b_27) - (unsigned char)'X') == 0) || 
        ((int)(int)(*(b_27) - (unsigned char)'x') == 0)))
      break;

    /* Line: 113       : MOVE               : customer.cob */
#line 113 "customer.cob"
    module->statement = STMT_MOVE;
#line 196 "customer.c"
    module->module_stmt = 0x00100071;
    cob_trace_statement (STMT_MOVE);
    cob_move ((cob_field *)&c_6, &f_26);

    /* Line: 114       : MOVE               : customer.cob */
#line 114 "customer.cob"
    module->statement = STMT_MOVE;
#line 204 "customer.c"
    module->module_stmt = 0x00100072;
    cob_trace_statement (STMT_MOVE);
    memcpy (b_43, "CHOOSE AN OPTION              ", 30);

    /* Line: 115       : MOVE               : customer.cob */
#line 115 "customer.cob"
    module->statement = STMT_MOVE;
#line 212 "customer.c"
    module->module_stmt = 0x00100073;
    cob_trace_statement (STMT_MOVE);
    *(b_27) = 32;

    /* Line: 116       : DISPLAY            : customer.cob */
#line 116 "customer.cob"
    module->statement = STMT_DISPLAY;
#line 220 "customer.c"
    module->module_stmt = 0x00100074;
    cob_trace_statement (STMT_DISPLAY);
    cob_move (&f_43, &f_205);
    cob_move (&f_24, &f_203);
    cob_screen_display (&fs_197, (cob_field *)&c_7, (cob_field *)&c_7, 1);

    /* Line: 117       : ACCEPT             : customer.cob */
#line 117 "customer.cob"
    module->statement = STMT_ACCEPT;
#line 230 "customer.c"
    module->module_stmt = 0x00100075;
    cob_trace_statement (STMT_ACCEPT);
    cob_move (&f_27, &f_213);
    cob_screen_accept (&fs_206, NULL, NULL, NULL, 1);
    cob_move (&f_213, &f_27);

    /* Line: 118       : EVALUATE           : customer.cob */
#line 118 "customer.cob"
    module->statement = STMT_EVALUATE;
#line 240 "customer.c"
    module->module_stmt = 0x00100076;
    cob_trace_statement (STMT_EVALUATE);

    /* Line: 119       : WHEN               : customer.cob */
#line 119 "customer.cob"
    module->statement = STMT_WHEN;
#line 247 "customer.c"
    module->module_stmt = 0x00100077;
    cob_trace_statement (STMT_WHEN);

    if (((int)(int)(*(b_27) - (unsigned char)'1') == 0))
    {

      /* Line: 120       : PERFORM            : customer.cob */
#line 120 "customer.cob"
      module->statement = STMT_PERFORM;
#line 257 "customer.c"
      module->module_stmt = 0x00100078;
      cob_trace_statement (STMT_PERFORM);
      /* PERFORM 002-INCLUDE THRU 002-INCLUDE-END */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 9;
      frame_ptr->return_address_ptr = &&l_23;
      goto l_7;
      l_23:
      frame_ptr--;
      goto l_5;
    }

    /* Line: 121       : WHEN               : customer.cob */
#line 121 "customer.cob"
    module->statement = STMT_WHEN;
#line 275 "customer.c"
    module->module_stmt = 0x00100079;
    cob_trace_statement (STMT_WHEN);

    if (((int)(int)(*(b_27) - (unsigned char)'2') == 0))
    {

      /* Line: 122       : PERFORM            : customer.cob */
#line 122 "customer.cob"
      module->statement = STMT_PERFORM;
#line 285 "customer.c"
      module->module_stmt = 0x0010007A;
      cob_trace_statement (STMT_PERFORM);
      /* PERFORM 003-CONSULT THRU 003-CONSULT-END */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 12;
      frame_ptr->return_address_ptr = &&l_24;
      goto l_10;
      l_24:
      frame_ptr--;
      goto l_5;
    }

    /* Line: 123       : WHEN               : customer.cob */
#line 123 "customer.cob"
    module->statement = STMT_WHEN;
#line 303 "customer.c"
    module->module_stmt = 0x0010007B;
    cob_trace_statement (STMT_WHEN);

    if (((int)(int)(*(b_27) - (unsigned char)'3') == 0))
    {

      /* Line: 124       : PERFORM            : customer.cob */
#line 124 "customer.cob"
      module->statement = STMT_PERFORM;
#line 313 "customer.c"
      module->module_stmt = 0x0010007C;
      cob_trace_statement (STMT_PERFORM);
      /* PERFORM 004-UPDATE THRU 004-UPDATE-END */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 15;
      frame_ptr->return_address_ptr = &&l_25;
      goto l_13;
      l_25:
      frame_ptr--;
      goto l_5;
    }

    /* Line: 125       : WHEN               : customer.cob */
#line 125 "customer.cob"
    module->statement = STMT_WHEN;
#line 331 "customer.c"
    module->module_stmt = 0x0010007D;
    cob_trace_statement (STMT_WHEN);

    if (((int)(int)(*(b_27) - (unsigned char)'4') == 0))
    {

      /* Line: 126       : PERFORM            : customer.cob */
#line 126 "customer.cob"
      module->statement = STMT_PERFORM;
#line 341 "customer.c"
      module->module_stmt = 0x0010007E;
      cob_trace_statement (STMT_PERFORM);
      /* PERFORM 005-DELETE THRU 005-DELETE-END */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 17;
      frame_ptr->return_address_ptr = &&l_26;
      goto l_16;
      l_26:
      frame_ptr--;
      goto l_5;
    }

    /* End EVALUATE */
    l_5:;
  }

  /* Line: 129       : Paragraph 001-FINISH              : customer.cob */
#line 129 "customer.cob"
  PARAGRAPH_001__FINISH_l_6:	module->statement = STMT_ENTRY;
#line 363 "customer.c"
  module->module_stmt = 0x00100081;
  module->paragraph_name = st_3;
  cob_trace_para (st_3);

  /* Line: 130       : CLOSE              : customer.cob */
#line 130 "customer.cob"
  module->statement = STMT_CLOSE;
#line 371 "customer.c"
  module->module_stmt = 0x00100082;
  cob_trace_statement (STMT_CLOSE);
  cob_close (h_FILE1, &f_33, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_27;
    goto l_1;
    l_27:
    frame_ptr--;
  }

  /* Line: 131       : STOP RUN           : customer.cob */
#line 131 "customer.cob"
  module->statement = STMT_STOP_RUN;
#line 391 "customer.c"
  module->module_stmt = 0x00100083;
  cob_trace_statement (STMT_STOP_RUN);
  cob_stop_run (b_2);

  /* Line: 134       : Paragraph 002-INCLUDE             : customer.cob */
  l_7:;
#line 134 "customer.cob"
  PARAGRAPH_002__INCLUDE_l_7:	module->statement = STMT_ENTRY;
#line 400 "customer.c"
  module->module_stmt = 0x00100086;
  module->paragraph_name = st_4;
  cob_trace_para (st_4);

  /* Line: 135       : MOVE               : customer.cob */
#line 135 "customer.cob"
  module->statement = STMT_MOVE;
#line 408 "customer.c"
  module->module_stmt = 0x00100087;
  cob_trace_statement (STMT_MOVE);
  memcpy (b_24 + 12, "INCLUDE             ", 20);

  /* Line: 136       : MOVE               : customer.cob */
#line 136 "customer.cob"
  module->statement = STMT_MOVE;
#line 416 "customer.c"
  module->module_stmt = 0x00100088;
  cob_trace_statement (STMT_MOVE);
  cob_move ((cob_field *)&c_8, &f_43);

  /* Line: 137       : DISPLAY            : customer.cob */
#line 137 "customer.cob"
  module->statement = STMT_DISPLAY;
#line 424 "customer.c"
  module->module_stmt = 0x00100089;
  cob_trace_statement (STMT_DISPLAY);
  cob_move (&f_43, &f_205);
  cob_move (&f_24, &f_203);
  cob_screen_display (&fs_197, (cob_field *)&c_7, (cob_field *)&c_7, 1);

  /* Line: 138       : MOVE               : customer.cob */
#line 138 "customer.cob"
  module->statement = STMT_MOVE;
#line 434 "customer.c"
  module->module_stmt = 0x0010008A;
  cob_trace_statement (STMT_MOVE);
  memset (b_23, 32, 109);

  /* Line: 139       : Paragraph 002-INCLUDE-LOOP        : customer.cob */
  l_8:;
#line 139 "customer.cob"
  PARAGRAPH_002__INCLUDE__LOOP_l_8:	module->statement = STMT_ENTRY;
#line 443 "customer.c"
  module->module_stmt = 0x0010008B;
  module->paragraph_name = st_5;
  cob_trace_para (st_5);

  /* Line: 140       : ACCEPT             : customer.cob */
#line 140 "customer.cob"
  module->statement = STMT_ACCEPT;
#line 451 "customer.c"
  module->module_stmt = 0x0010008C;
  cob_trace_statement (STMT_ACCEPT);
  cob_move (&f_21, &f_222);
  cob_move (&f_20, &f_220);
  cob_move (&f_19, &f_217);
  cob_screen_accept (&fs_214, NULL, NULL, NULL, 1);
  cob_move (&f_222, &f_21);
  cob_move (&f_220, &f_20);
  cob_move (&f_217, &f_19);

  /* Line: 141       : IF                 : customer.cob */
#line 141 "customer.cob"
  module->statement = STMT_IF;
#line 465 "customer.c"
  module->module_stmt = 0x0010008D;
  cob_trace_statement (STMT_IF);
  if (((int)cob_cmp_numdisp (b_227, 4, 2005LL, 0) == 0))
  {

    /* Line: 142       : GO TO              : customer.cob */
#line 142 "customer.cob"
    module->statement = STMT_GO_TO;
#line 474 "customer.c"
    module->module_stmt = 0x0010008E;
    cob_trace_statement (STMT_GO_TO);
    goto l_9;
  }

  /* Line: 144       : IF                 : customer.cob */
#line 144 "customer.cob"
  module->statement = STMT_IF;
#line 483 "customer.c"
  module->module_stmt = 0x00100090;
  cob_trace_statement (STMT_IF);
  if ((((int)memcmp (b_23 + 9, COB_SPACES_ALPHABETIC, 40) == 0) || 
      ((int)memcmp (b_23 + 49, COB_SPACES_ALPHABETIC, 40) == 0)))
  {

    /* Line: 145       : MOVE               : customer.cob */
#line 145 "customer.cob"
    module->statement = STMT_MOVE;
#line 493 "customer.c"
    module->module_stmt = 0x00100091;
    cob_trace_statement (STMT_MOVE);
    cob_move ((cob_field *)&c_9, &f_44);

    /* Line: 146       : PERFORM            : customer.cob */
#line 146 "customer.cob"
    module->statement = STMT_PERFORM;
#line 501 "customer.c"
    module->module_stmt = 0x00100092;
    cob_trace_statement (STMT_PERFORM);
    /* PERFORM 008-SHOW-ERROR */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 21;
    frame_ptr->return_address_ptr = &&l_28;
    goto l_21;
    l_28:
    frame_ptr--;

    /* Line: 147       : GO TO              : customer.cob */
#line 147 "customer.cob"
    module->statement = STMT_GO_TO;
#line 517 "customer.c"
    module->module_stmt = 0x00100093;
    cob_trace_statement (STMT_GO_TO);
    goto l_8;
  }

  /* Line: 149       : WRITE              : customer.cob */
#line 149 "customer.cob"
  module->statement = STMT_WRITE;
#line 526 "customer.c"
  module->module_stmt = 0x00100095;
  cob_trace_statement (STMT_WRITE);
  cob_write (h_FILE1, &f_17, 0, &f_33, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    if (cob_glob_ptr->cob_exception_code == 0x0506)
    {

      /* Line: 151       : MOVE               : customer.cob */
#line 151 "customer.cob"
      module->statement = STMT_MOVE;
#line 538 "customer.c"
      module->module_stmt = 0x00100097;
      cob_trace_statement (STMT_MOVE);
      cob_move ((cob_field *)&c_10, &f_44);

      /* Line: 152       : PERFORM            : customer.cob */
#line 152 "customer.cob"
      module->statement = STMT_PERFORM;
#line 546 "customer.c"
      module->module_stmt = 0x00100098;
      cob_trace_statement (STMT_PERFORM);
      /* PERFORM 008-SHOW-ERROR */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 21;
      frame_ptr->return_address_ptr = &&l_29;
      goto l_21;
      l_29:
      frame_ptr--;

      /* Line: 153       : MOVE               : customer.cob */
#line 153 "customer.cob"
      module->statement = STMT_MOVE;
#line 562 "customer.c"
      module->module_stmt = 0x00100099;
      cob_trace_statement (STMT_MOVE);
      memset (b_23, 48, 9);
    }
    else
    {
      /* USE PROCEDURE Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_30;
      goto l_1;
      l_30:
      frame_ptr--;
    }
  }

  /* Line: 155       : GO TO              : customer.cob */
#line 155 "customer.cob"
  module->statement = STMT_GO_TO;
#line 584 "customer.c"
  module->module_stmt = 0x0010009B;
  cob_trace_statement (STMT_GO_TO);
  goto l_8;

  /* Line: 156       : Paragraph 002-INCLUDE-END         : customer.cob */
  l_9:;
#line 156 "customer.cob"
  PARAGRAPH_002__INCLUDE__END_l_9:	module->statement = STMT_ENTRY;
#line 593 "customer.c"
  module->module_stmt = 0x0010009C;
  module->paragraph_name = st_6;
  cob_trace_para (st_6);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Line: 159       : Paragraph 003-CONSULT             : customer.cob */
  l_10:;
#line 159 "customer.cob"
  PARAGRAPH_003__CONSULT_l_10:	module->statement = STMT_ENTRY;
#line 606 "customer.c"
  module->module_stmt = 0x0010009F;
  module->paragraph_name = st_7;
  cob_trace_para (st_7);

  /* Line: 160       : MOVE               : customer.cob */
#line 160 "customer.cob"
  module->statement = STMT_MOVE;
#line 614 "customer.c"
  module->module_stmt = 0x001000A0;
  cob_trace_statement (STMT_MOVE);
  memcpy (b_24 + 12, "CONSULT             ", 20);

  /* Line: 161       : MOVE               : customer.cob */
#line 161 "customer.cob"
  module->statement = STMT_MOVE;
#line 622 "customer.c"
  module->module_stmt = 0x001000A1;
  cob_trace_statement (STMT_MOVE);
  cob_move ((cob_field *)&c_8, &f_43);

  /* Line: 162       : DISPLAY            : customer.cob */
#line 162 "customer.cob"
  module->statement = STMT_DISPLAY;
#line 630 "customer.c"
  module->module_stmt = 0x001000A2;
  cob_trace_statement (STMT_DISPLAY);
  cob_move (&f_43, &f_205);
  cob_move (&f_24, &f_203);
  cob_screen_display (&fs_197, (cob_field *)&c_7, (cob_field *)&c_7, 1);

  /* Line: 163       : Paragraph 003-CONSULT-LOOP        : customer.cob */
  l_11:;
#line 163 "customer.cob"
  PARAGRAPH_003__CONSULT__LOOP_l_11:	module->statement = STMT_ENTRY;
#line 641 "customer.c"
  module->module_stmt = 0x001000A3;
  module->paragraph_name = st_8;
  cob_trace_para (st_8);

  /* Line: 164       : MOVE               : customer.cob */
#line 164 "customer.cob"
  module->statement = STMT_MOVE;
#line 649 "customer.c"
  module->module_stmt = 0x001000A4;
  cob_trace_statement (STMT_MOVE);
  memset (b_23, 32, 109);

  /* Line: 165       : DISPLAY            : customer.cob */
#line 165 "customer.cob"
  module->statement = STMT_DISPLAY;
#line 657 "customer.c"
  module->module_stmt = 0x001000A5;
  cob_trace_statement (STMT_DISPLAY);
  cob_move (&f_21, &f_222);
  cob_move (&f_20, &f_220);
  cob_move (&f_19, &f_217);
  cob_screen_display (&fs_214, (cob_field *)&c_7, (cob_field *)&c_7, 1);

  /* Line: 166       : PERFORM            : customer.cob */
#line 166 "customer.cob"
  module->statement = STMT_PERFORM;
#line 668 "customer.c"
  module->module_stmt = 0x001000A6;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM 006-READ-CUSTOMER THRU 006-READ-CUSTOMER-END */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 19;
  frame_ptr->return_address_ptr = &&l_31;
  goto l_18;
  l_31:
  frame_ptr--;

  /* Line: 167       : IF                 : customer.cob */
#line 167 "customer.cob"
  module->statement = STMT_IF;
#line 684 "customer.c"
  module->module_stmt = 0x001000A7;
  cob_trace_statement (STMT_IF);
  if (((int)cob_cmp_numdisp (b_33, 2, 99LL, 0) == 0))
  {

    /* Line: 168       : GO TO              : customer.cob */
#line 168 "customer.cob"
    module->statement = STMT_GO_TO;
#line 693 "customer.c"
    module->module_stmt = 0x001000A8;
    cob_trace_statement (STMT_GO_TO);
    goto l_12;
  }

  /* Line: 170       : IF                 : customer.cob */
#line 170 "customer.cob"
  module->statement = STMT_IF;
#line 702 "customer.c"
  module->module_stmt = 0x001000AA;
  cob_trace_statement (STMT_IF);
  if (((int)cob_cmp_numdisp (b_33, 2, 0LL, 0) == 0))
  {

    /* Line: 171       : DISPLAY            : customer.cob */
#line 171 "customer.cob"
    module->statement = STMT_DISPLAY;
#line 711 "customer.c"
    module->module_stmt = 0x001000AB;
    cob_trace_statement (STMT_DISPLAY);
    cob_move (&f_21, &f_222);
    cob_move (&f_20, &f_220);
    cob_screen_display (&fs_218, (cob_field *)&c_7, (cob_field *)&c_7, 1);

    /* Line: 172       : MOVE               : customer.cob */
#line 172 "customer.cob"
    module->statement = STMT_MOVE;
#line 721 "customer.c"
    module->module_stmt = 0x001000AC;
    cob_trace_statement (STMT_MOVE);
    cob_move ((cob_field *)&c_11, &f_44);

    /* Line: 173       : PERFORM            : customer.cob */
#line 173 "customer.cob"
    module->statement = STMT_PERFORM;
#line 729 "customer.c"
    module->module_stmt = 0x001000AD;
    cob_trace_statement (STMT_PERFORM);
    /* PERFORM 008-SHOW-ERROR */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 21;
    frame_ptr->return_address_ptr = &&l_32;
    goto l_21;
    l_32:
    frame_ptr--;
  }

  /* Line: 175       : GO TO              : customer.cob */
#line 175 "customer.cob"
  module->statement = STMT_GO_TO;
#line 746 "customer.c"
  module->module_stmt = 0x001000AF;
  cob_trace_statement (STMT_GO_TO);
  goto l_11;

  /* Line: 176       : Paragraph 003-CONSULT-END         : customer.cob */
  l_12:;
#line 176 "customer.cob"
  PARAGRAPH_003__CONSULT__END_l_12:	module->statement = STMT_ENTRY;
#line 755 "customer.c"
  module->module_stmt = 0x001000B0;
  module->paragraph_name = st_9;
  cob_trace_para (st_9);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 12)
    goto *frame_ptr->return_address_ptr;

  /* Line: 179       : Paragraph 004-UPDATE              : customer.cob */
  l_13:;
#line 179 "customer.cob"
  PARAGRAPH_004__UPDATE_l_13:	module->statement = STMT_ENTRY;
#line 768 "customer.c"
  module->module_stmt = 0x001000B3;
  module->paragraph_name = st_10;
  cob_trace_para (st_10);

  /* Line: 180       : MOVE               : customer.cob */
#line 180 "customer.cob"
  module->statement = STMT_MOVE;
#line 776 "customer.c"
  module->module_stmt = 0x001000B4;
  cob_trace_statement (STMT_MOVE);
  memcpy (b_24 + 12, "UPDATE              ", 20);

  /* Line: 181       : MOVE               : customer.cob */
#line 181 "customer.cob"
  module->statement = STMT_MOVE;
#line 784 "customer.c"
  module->module_stmt = 0x001000B5;
  cob_trace_statement (STMT_MOVE);
  cob_move ((cob_field *)&c_8, &f_43);

  /* Line: 182       : DISPLAY            : customer.cob */
#line 182 "customer.cob"
  module->statement = STMT_DISPLAY;
#line 792 "customer.c"
  module->module_stmt = 0x001000B6;
  cob_trace_statement (STMT_DISPLAY);
  cob_move (&f_43, &f_205);
  cob_move (&f_24, &f_203);
  cob_screen_display (&fs_197, (cob_field *)&c_7, (cob_field *)&c_7, 1);

  /* Line: 183       : Paragraph 004-UPDATE-LOOP         : customer.cob */
  l_14:;
#line 183 "customer.cob"
  PARAGRAPH_004__UPDATE__LOOP_l_14:	module->statement = STMT_ENTRY;
#line 803 "customer.c"
  module->module_stmt = 0x001000B7;
  module->paragraph_name = st_11;
  cob_trace_para (st_11);

  /* Line: 184       : MOVE               : customer.cob */
#line 184 "customer.cob"
  module->statement = STMT_MOVE;
#line 811 "customer.c"
  module->module_stmt = 0x001000B8;
  cob_trace_statement (STMT_MOVE);
  memset (b_23, 32, 109);

  /* Line: 185       : DISPLAY            : customer.cob */
#line 185 "customer.cob"
  module->statement = STMT_DISPLAY;
#line 819 "customer.c"
  module->module_stmt = 0x001000B9;
  cob_trace_statement (STMT_DISPLAY);
  cob_move (&f_21, &f_222);
  cob_move (&f_20, &f_220);
  cob_move (&f_19, &f_217);
  cob_screen_display (&fs_214, (cob_field *)&c_7, (cob_field *)&c_7, 1);

  /* Line: 186       : PERFORM            : customer.cob */
#line 186 "customer.cob"
  module->statement = STMT_PERFORM;
#line 830 "customer.c"
  module->module_stmt = 0x001000BA;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM 006-READ-CUSTOMER THRU 006-READ-CUSTOMER-END */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 19;
  frame_ptr->return_address_ptr = &&l_33;
  goto l_18;
  l_33:
  frame_ptr--;

  /* Line: 187       : IF                 : customer.cob */
#line 187 "customer.cob"
  module->statement = STMT_IF;
#line 846 "customer.c"
  module->module_stmt = 0x001000BB;
  cob_trace_statement (STMT_IF);
  if (((int)cob_cmp_numdisp (b_33, 2, 99LL, 0) == 0))
  {

    /* Line: 188       : GO TO              : customer.cob */
#line 188 "customer.cob"
    module->statement = STMT_GO_TO;
#line 855 "customer.c"
    module->module_stmt = 0x001000BC;
    cob_trace_statement (STMT_GO_TO);
    goto l_15;
  }

  /* Line: 190       : IF                 : customer.cob */
#line 190 "customer.cob"
  module->statement = STMT_IF;
#line 864 "customer.c"
  module->module_stmt = 0x001000BE;
  cob_trace_statement (STMT_IF);
  if (((int)cob_cmp_numdisp (b_33, 2, 0LL, 0) == 0))
  {

    /* Line: 191       : ACCEPT             : customer.cob */
#line 191 "customer.cob"
    module->statement = STMT_ACCEPT;
#line 873 "customer.c"
    module->module_stmt = 0x001000BF;
    cob_trace_statement (STMT_ACCEPT);
    cob_move (&f_21, &f_222);
    cob_move (&f_20, &f_220);
    cob_screen_accept (&fs_218, NULL, NULL, NULL, 1);
    cob_move (&f_222, &f_21);
    cob_move (&f_220, &f_20);

    /* Line: 192       : IF                 : customer.cob */
#line 192 "customer.cob"
    module->statement = STMT_IF;
#line 885 "customer.c"
    module->module_stmt = 0x001000C0;
    cob_trace_statement (STMT_IF);
    if (((int)cob_cmp_numdisp (b_227, 4, 2005LL, 0) == 0))
    {

      /* Line: 193       : GO TO              : customer.cob */
#line 193 "customer.cob"
      module->statement = STMT_GO_TO;
#line 894 "customer.c"
      module->module_stmt = 0x001000C1;
      cob_trace_statement (STMT_GO_TO);
      goto l_14;
    }
  }
  else
  {
    /* ELSE */

    /* Line: 196       : GO TO              : customer.cob */
#line 196 "customer.cob"
    module->statement = STMT_GO_TO;
#line 907 "customer.c"
    module->module_stmt = 0x001000C4;
    cob_trace_statement (STMT_GO_TO);
    goto l_14;
  }

  /* Line: 198       : REWRITE            : customer.cob */
#line 198 "customer.cob"
  module->statement = STMT_REWRITE;
#line 916 "customer.c"
  module->module_stmt = 0x001000C6;
  cob_trace_statement (STMT_REWRITE);
  cob_rewrite (h_FILE1, &f_17, 0, &f_33);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    if (cob_glob_ptr->cob_exception_code == 0x0506)
    {

      /* Line: 200       : MOVE               : customer.cob */
#line 200 "customer.cob"
      module->statement = STMT_MOVE;
#line 928 "customer.c"
      module->module_stmt = 0x001000C8;
      cob_trace_statement (STMT_MOVE);
      cob_move ((cob_field *)&c_12, &f_44);

      /* Line: 201       : PERFORM            : customer.cob */
#line 201 "customer.cob"
      module->statement = STMT_PERFORM;
#line 936 "customer.c"
      module->module_stmt = 0x001000C9;
      cob_trace_statement (STMT_PERFORM);
      /* PERFORM 008-SHOW-ERROR */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 21;
      frame_ptr->return_address_ptr = &&l_34;
      goto l_21;
      l_34:
      frame_ptr--;
    }
    else
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_35;
      goto l_1;
      l_35:
      frame_ptr--;
    }
  }
  else
  {

    /* Line: 203       : CONTINUE           : customer.cob */
#line 203 "customer.cob"
    module->statement = STMT_CONTINUE;
#line 968 "customer.c"
    module->module_stmt = 0x001000CB;
    cob_trace_statement (STMT_CONTINUE);
    ;
  }

  /* Line: 205       : GO TO              : customer.cob */
#line 205 "customer.cob"
  module->statement = STMT_GO_TO;
#line 977 "customer.c"
  module->module_stmt = 0x001000CD;
  cob_trace_statement (STMT_GO_TO);
  goto l_14;

  /* Line: 206       : Paragraph 004-UPDATE-END          : customer.cob */
  l_15:;
#line 206 "customer.cob"
  PARAGRAPH_004__UPDATE__END_l_15:	module->statement = STMT_ENTRY;
#line 986 "customer.c"
  module->module_stmt = 0x001000CE;
  module->paragraph_name = st_12;
  cob_trace_para (st_12);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 15)
    goto *frame_ptr->return_address_ptr;

  /* Line: 209       : Paragraph 005-DELETE              : customer.cob */
  l_16:;
#line 209 "customer.cob"
  PARAGRAPH_005__DELETE_l_16:	module->statement = STMT_ENTRY;
#line 999 "customer.c"
  module->module_stmt = 0x001000D1;
  module->paragraph_name = st_13;
  cob_trace_para (st_13);

  /* Line: 210       : MOVE               : customer.cob */
#line 210 "customer.cob"
  module->statement = STMT_MOVE;
#line 1007 "customer.c"
  module->module_stmt = 0x001000D2;
  cob_trace_statement (STMT_MOVE);
  memcpy (b_24 + 12, "DELETE              ", 20);

  /* Line: 211       : MOVE               : customer.cob */
#line 211 "customer.cob"
  module->statement = STMT_MOVE;
#line 1015 "customer.c"
  module->module_stmt = 0x001000D3;
  cob_trace_statement (STMT_MOVE);
  cob_move ((cob_field *)&c_8, &f_43);

  /* Line: 212       : DISPLAY            : customer.cob */
#line 212 "customer.cob"
  module->statement = STMT_DISPLAY;
#line 1023 "customer.c"
  module->module_stmt = 0x001000D4;
  cob_trace_statement (STMT_DISPLAY);
  cob_move (&f_43, &f_205);
  cob_move (&f_24, &f_203);
  cob_screen_display (&fs_197, (cob_field *)&c_7, (cob_field *)&c_7, 1);

  /* Line: 213       : MOVE               : customer.cob */
#line 213 "customer.cob"
  module->statement = STMT_MOVE;
#line 1033 "customer.c"
  module->module_stmt = 0x001000D5;
  cob_trace_statement (STMT_MOVE);
  memset (b_23, 32, 109);

  /* Line: 214       : DISPLAY            : customer.cob */
#line 214 "customer.cob"
  module->statement = STMT_DISPLAY;
#line 1041 "customer.c"
  module->module_stmt = 0x001000D6;
  cob_trace_statement (STMT_DISPLAY);
  cob_move (&f_21, &f_222);
  cob_move (&f_20, &f_220);
  cob_move (&f_19, &f_217);
  cob_screen_display (&fs_214, (cob_field *)&c_7, (cob_field *)&c_7, 1);

  /* Line: 215       : PERFORM            : customer.cob */
#line 215 "customer.cob"
  module->statement = STMT_PERFORM;
#line 1052 "customer.c"
  module->module_stmt = 0x001000D7;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM 006-READ-CUSTOMER THRU 006-READ-CUSTOMER-END */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 19;
  frame_ptr->return_address_ptr = &&l_36;
  goto l_18;
  l_36:
  frame_ptr--;

  /* Line: 216       : IF                 : customer.cob */
#line 216 "customer.cob"
  module->statement = STMT_IF;
#line 1068 "customer.c"
  module->module_stmt = 0x001000D8;
  cob_trace_statement (STMT_IF);
  if (((int)cob_cmp_numdisp (b_33, 2, 99LL, 0) == 0))
  {

    /* Line: 217       : GO TO              : customer.cob */
#line 217 "customer.cob"
    module->statement = STMT_GO_TO;
#line 1077 "customer.c"
    module->module_stmt = 0x001000D9;
    cob_trace_statement (STMT_GO_TO);
    goto l_17;
  }

  /* Line: 219       : IF                 : customer.cob */
#line 219 "customer.cob"
  module->statement = STMT_IF;
#line 1086 "customer.c"
  module->module_stmt = 0x001000DB;
  cob_trace_statement (STMT_IF);
  if (!((int)cob_cmp_numdisp (b_33, 2, 0LL, 0) == 0))
  {

    /* Line: 220       : GO TO              : customer.cob */
#line 220 "customer.cob"
    module->statement = STMT_GO_TO;
#line 1095 "customer.c"
    module->module_stmt = 0x001000DC;
    cob_trace_statement (STMT_GO_TO);
    goto l_16;
  }

  /* Line: 222       : DISPLAY            : customer.cob */
#line 222 "customer.cob"
  module->statement = STMT_DISPLAY;
#line 1104 "customer.c"
  module->module_stmt = 0x001000DE;
  cob_trace_statement (STMT_DISPLAY);
  cob_move (&f_21, &f_222);
  cob_move (&f_20, &f_220);
  cob_screen_display (&fs_218, (cob_field *)&c_7, (cob_field *)&c_7, 1);

  /* Line: 223       : MOVE               : customer.cob */
#line 223 "customer.cob"
  module->statement = STMT_MOVE;
#line 1114 "customer.c"
  module->module_stmt = 0x001000DF;
  cob_trace_statement (STMT_MOVE);
  *(b_37) = 78;

  /* Line: 224       : MOVE               : customer.cob */
#line 224 "customer.cob"
  module->statement = STMT_MOVE;
#line 1122 "customer.c"
  module->module_stmt = 0x001000E0;
  cob_trace_statement (STMT_MOVE);
  cob_move ((cob_field *)&c_13, &f_44);

  /* Line: 225       : ACCEPT             : customer.cob */
#line 225 "customer.cob"
  module->statement = STMT_ACCEPT;
#line 1130 "customer.c"
  module->module_stmt = 0x001000E1;
  cob_trace_statement (STMT_ACCEPT);
  cob_move (&f_44, &f_225);
  cob_screen_accept (&fs_223, NULL, NULL, NULL, 1);
  cob_move (&f_226, &f_37);

  /* Line: 226       : IF                 : customer.cob */
#line 226 "customer.cob"
  module->statement = STMT_IF;
#line 1140 "customer.c"
  module->module_stmt = 0x001000E2;
  cob_trace_statement (STMT_IF);
  if (!(((int)(int)(*(b_37) - (unsigned char)'Y') == 0) || 
      ((int)(int)(*(b_37) - (unsigned char)'y') == 0)))
  {

    /* Line: 227       : GO TO              : customer.cob */
#line 227 "customer.cob"
    module->statement = STMT_GO_TO;
#line 1150 "customer.c"
    module->module_stmt = 0x001000E3;
    cob_trace_statement (STMT_GO_TO);
    goto l_17;
  }

  /* Line: 229       : DELETE             : customer.cob */
#line 229 "customer.cob"
  module->statement = STMT_DELETE;
#line 1159 "customer.c"
  module->module_stmt = 0x001000E5;
  cob_trace_statement (STMT_DELETE);
  cob_delete (h_FILE1, &f_33);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    if (cob_glob_ptr->cob_exception_code == 0x0506)
    {

      /* Line: 231       : MOVE               : customer.cob */
#line 231 "customer.cob"
      module->statement = STMT_MOVE;
#line 1171 "customer.c"
      module->module_stmt = 0x001000E7;
      cob_trace_statement (STMT_MOVE);
      cob_move ((cob_field *)&c_14, &f_44);

      /* Line: 232       : PERFORM            : customer.cob */
#line 232 "customer.cob"
      module->statement = STMT_PERFORM;
#line 1179 "customer.c"
      module->module_stmt = 0x001000E8;
      cob_trace_statement (STMT_PERFORM);
      /* PERFORM 008-SHOW-ERROR */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 21;
      frame_ptr->return_address_ptr = &&l_37;
      goto l_21;
      l_37:
      frame_ptr--;
    }
    else
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_38;
      goto l_1;
      l_38:
      frame_ptr--;
    }
  }

  /* Line: 234       : Paragraph 005-DELETE-END          : customer.cob */
  l_17:;
#line 234 "customer.cob"
  PARAGRAPH_005__DELETE__END_l_17:	module->statement = STMT_ENTRY;
#line 1210 "customer.c"
  module->module_stmt = 0x001000EA;
  module->paragraph_name = st_14;
  cob_trace_para (st_14);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 17)
    goto *frame_ptr->return_address_ptr;

  /* Line: 238       : Paragraph 006-READ-CUSTOMER       : customer.cob */
  l_18:;
#line 238 "customer.cob"
  PARAGRAPH_006__READ__CUSTOMER_l_18:	module->statement = STMT_ENTRY;
#line 1223 "customer.c"
  module->module_stmt = 0x001000EE;
  module->paragraph_name = st_15;
  cob_trace_para (st_15);

  /* Line: 239       : ACCEPT             : customer.cob */
#line 239 "customer.cob"
  module->statement = STMT_ACCEPT;
#line 1231 "customer.c"
  module->module_stmt = 0x001000EF;
  cob_trace_statement (STMT_ACCEPT);
  cob_move (&f_19, &f_217);
  cob_screen_accept (&fs_215, NULL, NULL, NULL, 1);
  cob_move (&f_217, &f_19);

  /* Line: 240       : IF                 : customer.cob */
#line 240 "customer.cob"
  module->statement = STMT_IF;
#line 1241 "customer.c"
  module->module_stmt = 0x001000F0;
  cob_trace_statement (STMT_IF);
  if (!((int)cob_cmp_numdisp (b_227, 4, 2005LL, 0) == 0))
  {

    /* Line: 241       : READ               : customer.cob */
#line 241 "customer.cob"
    module->statement = STMT_READ;
#line 1250 "customer.c"
    module->module_stmt = 0x001000F1;
    cob_trace_statement (STMT_READ);
    cob_read (h_FILE1, &f_18, &f_33, 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0506)
      {

        /* Line: 243       : MOVE               : customer.cob */
#line 243 "customer.cob"
        module->statement = STMT_MOVE;
#line 1262 "customer.c"
        module->module_stmt = 0x001000F3;
        cob_trace_statement (STMT_MOVE);
        cob_move ((cob_field *)&c_15, &f_44);

        /* Line: 244       : PERFORM            : customer.cob */
#line 244 "customer.cob"
        module->statement = STMT_PERFORM;
#line 1270 "customer.c"
        module->module_stmt = 0x001000F4;
        cob_trace_statement (STMT_PERFORM);
        /* PERFORM 008-SHOW-ERROR */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
        	cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 21;
        frame_ptr->return_address_ptr = &&l_39;
        goto l_21;
        l_39:
        frame_ptr--;
      }
      else
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
        	cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_40;
        goto l_1;
        l_40:
        frame_ptr--;
      }
    }
  }
  else
  {
    /* ELSE */

    /* Line: 247       : MOVE               : customer.cob */
#line 247 "customer.cob"
    module->statement = STMT_MOVE;
#line 1304 "customer.c"
    module->module_stmt = 0x001000F7;
    cob_trace_statement (STMT_MOVE);
    memset (b_33, 57, 2);
  }

  /* Line: 249       : Paragraph 006-READ-CUSTOMER-END   : customer.cob */
  l_19:;
#line 249 "customer.cob"
  PARAGRAPH_006__READ__CUSTOMER__END_l_19:	module->statement = STMT_ENTRY;
#line 1314 "customer.c"
  module->module_stmt = 0x001000F9;
  module->paragraph_name = st_16;
  cob_trace_para (st_16);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 19)
    goto *frame_ptr->return_address_ptr;

  /* Line: 253       : Paragraph 007-OPEN-FILES          : customer.cob */
  l_20:;
#line 253 "customer.cob"
  PARAGRAPH_007__OPEN__FILES_l_20:	module->statement = STMT_ENTRY;
#line 1327 "customer.c"
  module->module_stmt = 0x001000FD;
  module->paragraph_name = st_17;
  cob_trace_para (st_17);

  /* Line: 254       : OPEN               : customer.cob */
#line 254 "customer.cob"
  module->statement = STMT_OPEN;
#line 1335 "customer.c"
  module->module_stmt = 0x001000FE;
  cob_trace_statement (STMT_OPEN);
  cob_open (h_FILE1, COB_OPEN_I_O, 0, &f_33);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_41;
    goto l_1;
    l_41:
    frame_ptr--;
  }

  /* Line: 255       : IF                 : customer.cob */
#line 255 "customer.cob"
  module->statement = STMT_IF;
#line 1355 "customer.c"
  module->module_stmt = 0x001000FF;
  cob_trace_statement (STMT_IF);
  if (((int)cob_cmp_numdisp (b_33, 2, 35LL, 0) == 0))
  {

    /* Line: 256       : OPEN               : customer.cob */
#line 256 "customer.cob"
    module->statement = STMT_OPEN;
#line 1364 "customer.c"
    module->module_stmt = 0x00100100;
    cob_trace_statement (STMT_OPEN);
    cob_open (h_FILE1, COB_OPEN_OUTPUT, 0, &f_33);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* USE PROCEDURE Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_42;
      goto l_1;
      l_42:
      frame_ptr--;
    }

    /* Line: 257       : CLOSE              : customer.cob */
#line 257 "customer.cob"
    module->statement = STMT_CLOSE;
#line 1384 "customer.c"
    module->module_stmt = 0x00100101;
    cob_trace_statement (STMT_CLOSE);
    cob_close (h_FILE1, &f_33, 0, 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* USE PROCEDURE Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_43;
      goto l_1;
      l_43:
      frame_ptr--;
    }

    /* Line: 258       : OPEN               : customer.cob */
#line 258 "customer.cob"
    module->statement = STMT_OPEN;
#line 1404 "customer.c"
    module->module_stmt = 0x00100102;
    cob_trace_statement (STMT_OPEN);
    cob_open (h_FILE1, COB_OPEN_I_O, 0, &f_33);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* USE PROCEDURE Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_44;
      goto l_1;
      l_44:
      frame_ptr--;
    }
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 20)
    goto *frame_ptr->return_address_ptr;

  /* Line: 263       : Paragraph 008-SHOW-ERROR          : customer.cob */
  l_21:;
#line 263 "customer.cob"
  PARAGRAPH_008__SHOW__ERROR_l_21:	module->statement = STMT_ENTRY;
#line 1430 "customer.c"
  module->module_stmt = 0x00100107;
  module->paragraph_name = st_18;
  cob_trace_para (st_18);

  /* Line: 264       : DISPLAY            : customer.cob */
#line 264 "customer.cob"
  module->statement = STMT_DISPLAY;
#line 1438 "customer.c"
  module->module_stmt = 0x00100108;
  cob_trace_statement (STMT_DISPLAY);
  cob_move (&f_44, &f_225);
  cob_screen_display (&fs_223, (cob_field *)&c_7, (cob_field *)&c_7, 1);

  /* Line: 265       : ACCEPT             : customer.cob */
#line 265 "customer.cob"
  module->statement = STMT_ACCEPT;
#line 1447 "customer.c"
  module->module_stmt = 0x00100109;
  cob_trace_statement (STMT_ACCEPT);
  cob_move (&f_44, &f_225);
  cob_screen_accept (&fs_223, NULL, NULL, NULL, 1);
  cob_move (&f_226, &f_37);

  /* Line: 266       : DISPLAY            : customer.cob */
#line 266 "customer.cob"
  module->statement = STMT_DISPLAY;
#line 1457 "customer.c"
  module->module_stmt = 0x0010010A;
  cob_trace_statement (STMT_DISPLAY);
  cob_move (&f_43, &f_205);
  cob_screen_display (&fs_204, (cob_field *)&c_7, (cob_field *)&c_7, 1);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 21)
    goto *frame_ptr->return_address_ptr;

  /* Line: 267       : last source line                  :customer.cob */
#line 267 "customer.cob"
  module->module_stmt = 0x0010010B;
#line 1470 "customer.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Trace program exit */
  cob_trace_exit (st_1);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : customer.cob */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  CUSTOMERS_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = &f_227;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field FILLER 2 */
#line 33 "customer.cob"
  cob_nop ();
#line 1542 "customer.c"
  memcpy (b_24, "CUSTOMERS - ", 12);
  /* initialize field WS-OP */
#line 34 "customer.cob"
  cob_nop ();
#line 1547 "customer.c"
  memset (b_24 + 12, 32, 20);

  /* initialize field WS-CHOICE */
#line 36 "customer.cob"
  cob_nop ();
#line 1553 "customer.c"
  *(cob_u8_ptr)(b_27) = (unsigned char)' ';

  /* initialize field FS-STAT */
#line 42 "customer.cob"
  cob_nop ();
#line 1559 "customer.c"
  memset (b_33, (unsigned char)'0', 2);

  /* initialize field WS-ERROR */
#line 46 "customer.cob"
  cob_nop ();
#line 1565 "customer.c"
  *(cob_u8_ptr)(b_37) = (unsigned char)' ';

  /* initialize field WS_NUMR */
#line 49 "customer.cob"
  cob_nop ();
#line 1571 "customer.c"
  memset (b_39, (unsigned char)'0', 3);

  /* initialize field WS-NUMC012 */
#line 50 "customer.cob"
  cob_nop ();
#line 1577 "customer.c"
  memset (b_40, (unsigned char)'0', 3);

  /* initialize field BACK-COLOR */
#line 51 "customer.cob"
  cob_nop ();
#line 1583 "customer.c"
  *(b_41) = 49;

  /* initialize field FRONT-COLOR */
#line 52 "customer.cob"
  cob_nop ();
#line 1589 "customer.c"
  *(b_42) = 54;

  /* initialize field WS-STATUS */
#line 54 "customer.cob"
  cob_nop ();
#line 1595 "customer.c"
  memset (b_43, (unsigned char)' ', 30);

  /* initialize field WS-ERRMSG */
#line 55 "customer.cob"
  cob_nop ();
#line 1601 "customer.c"
  memset (b_44, (unsigned char)' ', 80);

  /* initialize field COB-CRT-STATUS */
#line 102 "customer.cob"
  cob_nop ();
#line 1607 "customer.c"
  memset (b_227, (unsigned char)'0', 4);


  /* File initialization for FILE1 */
  cob_file_malloc (&h_FILE1, &k_FILE1, 1, 0);
  k_FILE1->field = &f_18;
  k_FILE1->tf_duplicates = 0;
  k_FILE1->offset = 0;
  h_FILE1->select_name = (const char *)"FILE1";
  h_FILE1->file_status = h_FILE1_status;
  memset (h_FILE1_status, '0', 2);
  h_FILE1->assign = (cob_field *)&c_16;
  h_FILE1->record = &f_23;
  h_FILE1->variable_record = NULL;
  h_FILE1->record_min = 109;
  h_FILE1->record_max = 109;
  h_FILE1->file = NULL;
  h_FILE1->organization = 3;
  h_FILE1->access_mode = 3;
  h_FILE1->lock_mode = 0;
  h_FILE1->open_mode = 0;
  h_FILE1->flag_optional = 0;
  h_FILE1->flag_line_adv = 0;
  h_FILE1->flag_select_features = 1;

  /* Initialize SCREEN items */
  /* initialize field SS-CLS */
#line 60 "customer.cob"
  cob_nop ();
#line 1637 "customer.c"
  memset (b_197, (unsigned char)' ', 64);

  /* initialize field FILLER 8 */
#line 78 "customer.cob"
  cob_nop ();
#line 1643 "customer.c"
  memcpy (b_206, "1 - INCLUDE", 11);
  /* initialize field FILLER 9 */
#line 79 "customer.cob"
  cob_nop ();
#line 1648 "customer.c"
  memcpy (b_206 + 11, "2 - CONSULT", 11);
  /* initialize field FILLER 10 */
#line 80 "customer.cob"
  cob_nop ();
#line 1653 "customer.c"
  memcpy (b_206 + 22, "3 - UPDATE", 10);
  /* initialize field FILLER 11 */
#line 81 "customer.cob"
  cob_nop ();
#line 1658 "customer.c"
  memcpy (b_206 + 32, "4 - DELETE", 10);
  /* initialize field FILLER 12 */
#line 82 "customer.cob"
  cob_nop ();
#line 1663 "customer.c"
  memcpy (b_206 + 42, "X - EXIT", 8);
  /* initialize field FILLER 13 */
#line 83 "customer.cob"
  cob_nop ();
#line 1668 "customer.c"
  memcpy (b_206 + 50, "CHOICE: ", 8);
  /* initialize field FILLER 14 */
#line 84 "customer.cob"
  cob_nop ();
#line 1673 "customer.c"
  *(cob_u8_ptr)(b_206 + 58) = (unsigned char)' ';

  /* initialize field FILLER 15 */
#line 88 "customer.cob"
  cob_nop ();
#line 1679 "customer.c"
  memcpy (b_214, "  PHONE:", 8);
  /* initialize field FILLER 16 */
#line 89 "customer.cob"
  cob_nop ();
#line 1684 "customer.c"
  cob_move (&cob_all_zero, &f_217);
  /* initialize field FILLER 17 */
#line 92 "customer.cob"
  cob_nop ();
#line 1689 "customer.c"
  memcpy (b_214 + 17, "   NAME:", 8);
  /* initialize field FILLER 18 */
#line 93 "customer.cob"
  cob_nop ();
#line 1694 "customer.c"
  memset (b_214 + 25, (unsigned char)' ', 40);
  /* initialize field FILLER 19 */
#line 94 "customer.cob"
  cob_nop ();
#line 1699 "customer.c"
  memcpy (b_214 + 65, "ADDRESS:", 8);
  /* initialize field FILLER 20 */
#line 95 "customer.cob"
  cob_nop ();
#line 1704 "customer.c"
  memset (b_214 + 73, (unsigned char)' ', 40);

  /* initialize field SS-ERROR */
#line 97 "customer.cob"
  cob_nop ();
#line 1710 "customer.c"
  memset (b_223, (unsigned char)' ', 81);

  COB_SET_SCREEN (fs_197, 0, 0x0, NULL, NULL, 
  		  &fs_198, NULL, NULL, 
  		  NULL, NULL, NULL, 
  		  NULL, NULL, NULL, 0);
  COB_SET_SCREEN (fs_198, 0, 0x0, &fs_202, NULL, 
  		  &fs_199, &fs_197, NULL, 
  		  NULL, NULL, NULL, 
  		  NULL, NULL, NULL, 0);
  COB_SET_SCREEN (fs_199, 1, 0x80, &fs_200, NULL, 
  		  NULL, &fs_198, &f_199, 
  		  NULL, NULL, NULL, 
  		  NULL, NULL, NULL, 0);
  COB_SET_SCREEN (fs_200, 1, 0x200, &fs_201, &fs_199, 
  		  NULL, &fs_198, &f_200, 
  		  NULL, (cob_field *)&c_17, (cob_field *)&c_17, 
  		  NULL, &f_41, NULL, 0);
  COB_SET_SCREEN (fs_201, 1, 0x200, NULL, &fs_200, 
  		  NULL, &fs_198, &f_201, 
  		  NULL, &f_39, (cob_field *)&c_17, 
  		  NULL, &f_41, NULL, 0);
  COB_SET_SCREEN (fs_202, 0, 0x0, &fs_204, &fs_198, 
  		  &fs_203, &fs_197, NULL, 
  		  NULL, NULL, NULL, 
  		  NULL, NULL, NULL, 0);
  COB_SET_SCREEN (fs_203, 1, 0x1000, NULL, NULL, 
  		  NULL, &fs_202, &f_203, 
  		  NULL, (cob_field *)&c_17, (cob_field *)&c_18, 
  		  &f_42, &f_41, NULL, 0);
  COB_SET_SCREEN (fs_204, 0, 0x0, NULL, &fs_202, 
  		  &fs_205, &fs_197, NULL, 
  		  NULL, NULL, NULL, 
  		  NULL, NULL, NULL, 0);
  COB_SET_SCREEN (fs_205, 1, 0x1200, NULL, NULL, 
  		  NULL, &fs_204, &f_205, 
  		  NULL, &f_39, (cob_field *)&c_19, 
  		  &f_42, &f_41, NULL, 0);
  COB_SET_SCREEN (fs_206, 0, 0x0, NULL, NULL, 
  		  &fs_207, NULL, NULL, 
  		  NULL, NULL, NULL, 
  		  (cob_field *)&c_20, NULL, NULL, 0);
  COB_SET_SCREEN (fs_207, 2, 0x0, &fs_208, NULL, 
  		  NULL, &fs_206, NULL, 
  		  &f_207, (cob_field *)&c_21, (cob_field *)&c_22, 
  		  (cob_field *)&c_20, NULL, NULL, 0);
  COB_SET_SCREEN (fs_208, 2, 0x0, &fs_209, &fs_207, 
  		  NULL, &fs_206, NULL, 
  		  &f_208, (cob_field *)&c_23, (cob_field *)&c_22, 
  		  (cob_field *)&c_20, NULL, NULL, 0);
  COB_SET_SCREEN (fs_209, 2, 0x0, &fs_210, &fs_208, 
  		  NULL, &fs_206, NULL, 
  		  &f_209, (cob_field *)&c_24, (cob_field *)&c_22, 
  		  (cob_field *)&c_20, NULL, NULL, 0);
  COB_SET_SCREEN (fs_210, 2, 0x0, &fs_211, &fs_209, 
  		  NULL, &fs_206, NULL, 
  		  &f_210, (cob_field *)&c_25, (cob_field *)&c_22, 
  		  (cob_field *)&c_20, NULL, NULL, 0);
  COB_SET_SCREEN (fs_211, 2, 0x0, &fs_212, &fs_210, 
  		  NULL, &fs_206, NULL, 
  		  &f_211, (cob_field *)&c_26, (cob_field *)&c_22, 
  		  (cob_field *)&c_20, NULL, NULL, 0);
  COB_SET_SCREEN (fs_212, 2, 0x0, &fs_213, &fs_211, 
  		  NULL, &fs_206, NULL, 
  		  &f_212, (cob_field *)&c_27, (cob_field *)&c_22, 
  		  (cob_field *)&c_20, NULL, NULL, 0);
  COB_SET_SCREEN (fs_213, 1, 0x200014, NULL, &fs_212, 
  		  NULL, &fs_206, &f_213, 
  		  NULL, (cob_field *)&c_27, (cob_field *)&c_28, 
  		  (cob_field *)&c_20, NULL, NULL, 0);
  COB_SET_SCREEN (fs_214, 0, 0x0, NULL, NULL, 
  		  &fs_215, NULL, NULL, 
  		  NULL, NULL, NULL, 
  		  NULL, NULL, NULL, 0);
  COB_SET_SCREEN (fs_215, 0, 0x0, &fs_218, NULL, 
  		  &fs_216, &fs_214, NULL, 
  		  NULL, NULL, NULL, 
  		  (cob_field *)&c_19, NULL, NULL, 0);
  COB_SET_SCREEN (fs_216, 2, 0x0, &fs_217, NULL, 
  		  NULL, &fs_215, NULL, 
  		  &f_216, (cob_field *)&c_25, (cob_field *)&c_25, 
  		  (cob_field *)&c_19, NULL, NULL, 0);
  COB_SET_SCREEN (fs_217, 1, 0x200004, NULL, &fs_216, 
  		  NULL, &fs_215, &f_217, 
  		  NULL, NULL, (cob_field *)&c_19, 
  		  (cob_field *)&c_19, NULL, NULL, 0);
  COB_SET_SCREEN (fs_218, 0, 0x0, NULL, &fs_215, 
  		  &fs_219, &fs_214, NULL, 
  		  NULL, NULL, NULL, 
  		  NULL, NULL, NULL, 0);
  COB_SET_SCREEN (fs_219, 2, 0x0, &fs_220, NULL, 
  		  NULL, &fs_218, NULL, 
  		  &f_219, (cob_field *)&c_26, (cob_field *)&c_25, 
  		  NULL, NULL, NULL, 0);
  COB_SET_SCREEN (fs_220, 1, 0x200004, &fs_221, &fs_219, 
  		  NULL, &fs_218, &f_220, 
  		  NULL, NULL, (cob_field *)&c_19, 
  		  NULL, NULL, NULL, 0);
  COB_SET_SCREEN (fs_221, 2, 0x0, &fs_222, &fs_220, 
  		  NULL, &fs_218, NULL, 
  		  &f_221, (cob_field *)&c_29, (cob_field *)&c_25, 
  		  NULL, NULL, NULL, 0);
  COB_SET_SCREEN (fs_222, 1, 0x200004, NULL, &fs_221, 
  		  NULL, &fs_218, &f_222, 
  		  NULL, NULL, (cob_field *)&c_19, 
  		  NULL, NULL, NULL, 0);
  COB_SET_SCREEN (fs_223, 0, 0x0, NULL, NULL, 
  		  &fs_224, NULL, NULL, 
  		  NULL, NULL, NULL, 
  		  NULL, NULL, NULL, 0);
  COB_SET_SCREEN (fs_224, 0, 0x1000, NULL, NULL, 
  		  &fs_225, &fs_223, NULL, 
  		  NULL, NULL, NULL, 
  		  (cob_field *)&c_30, (cob_field *)&c_28, NULL, 0);
  COB_SET_SCREEN (fs_225, 1, 0x1020, &fs_226, NULL, 
  		  NULL, &fs_224, &f_225, 
  		  NULL, &f_39, (cob_field *)&c_19, 
  		  (cob_field *)&c_30, (cob_field *)&c_28, NULL, 0);
  COB_SET_SCREEN (fs_226, 1, 0x201004, NULL, &fs_225, 
  		  NULL, &fs_224, &f_226, 
  		  NULL, NULL, (cob_field *)&c_19, 
  		  (cob_field *)&c_30, (cob_field *)&c_28, NULL, 0);

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'CUSTOMERS' */

/* Initialize module structure for CUSTOMERS */
static void CUSTOMERS_module_init (cob_module *module)
{
  module->module_name = "CUSTOMERS";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())CUSTOMERS;
  module->module_cancel.funcptr = (void *(*)())CUSTOMERS_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = ',';
  module->currency_symbol = '$';
  module->numeric_separator = '.';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 6;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

