/* Generated by           cobc 3.2.0 */
/* Generated from         customer.cob */
/* Generated at           set 13 2023 12:16:59 */
/* GnuCOBOL build date    Jul 28 2023 19:10:09 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -g -fsource-location -ftraceall -Q --coverage -A --coverage -v -O0 -x customer.cob */

/* Program local variables for 'CUSTOMERS' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* File FILE1 */
static cob_file_key	*k_FILE1 = NULL;
static cob_file		*h_FILE1 = NULL;
static unsigned char	h_FILE1_status[4];

/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Screens */

static cob_screen	fs_226;
static cob_screen	fs_225;
static cob_screen	fs_224;
static cob_screen	fs_223;
static cob_screen	fs_222;
static cob_screen	fs_221;
static cob_screen	fs_220;
static cob_screen	fs_219;
static cob_screen	fs_218;
static cob_screen	fs_217;
static cob_screen	fs_216;
static cob_screen	fs_215;
static cob_screen	fs_214;
static cob_screen	fs_213;
static cob_screen	fs_212;
static cob_screen	fs_211;
static cob_screen	fs_210;
static cob_screen	fs_209;
static cob_screen	fs_208;
static cob_screen	fs_207;
static cob_screen	fs_206;
static cob_screen	fs_205;
static cob_screen	fs_204;
static cob_screen	fs_203;
static cob_screen	fs_202;
static cob_screen	fs_201;
static cob_screen	fs_200;
static cob_screen	fs_199;
static cob_screen	fs_198;
static cob_screen	fs_197;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_23[109] __attribute__((aligned));	/* FILE1 Record */
static cob_u8_t	b_24[32] __attribute__((aligned));	/* WS-MODULE */
static cob_u8_t	b_27[1] __attribute__((aligned));	/* WS-CHOICE */
static cob_u8_t	b_33[2] __attribute__((aligned));	/* FS-STAT */
static cob_u8_t	b_37[1] __attribute__((aligned));	/* WS-ERROR */
static cob_u8_t	b_39[3] __attribute__((aligned));	/* WS_NUMR */
static cob_u8_t	b_40[3] __attribute__((aligned));	/* WS-NUMC012 */
static cob_u8_t	b_41[1] __attribute__((aligned));	/* BACK-COLOR */
static cob_u8_t	b_42[1] __attribute__((aligned));	/* FRONT-COLOR */
static cob_u8_t	b_43[30] __attribute__((aligned));	/* WS-STATUS */
static cob_u8_t	b_44[80] __attribute__((aligned));	/* WS-ERRMSG */
static cob_u8_t	b_197[64] __attribute__((aligned));	/* SS-CLS */
static cob_u8_t	b_206[59] __attribute__((aligned));	/* SS-MENU */
static cob_u8_t	b_214[113] __attribute__((aligned));	/* SS-RECORD-SCREEN */
static cob_u8_t	b_223[81] __attribute__((aligned));	/* SS-ERROR */
static cob_u8_t	b_227[4] __attribute__((aligned));	/* COB-CRT-STATUS */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17	= {109, b_23, &a_4};	/* FILE1-REC */
static cob_field f_18	= {9, b_23, &a_4};	/* FS-KEY */
static cob_field f_19	= {9, b_23, &a_7};	/* FS-PHONE */
static cob_field f_20	= {40, b_23 + 9, &a_3};	/* FS-NAME */
static cob_field f_21	= {40, b_23 + 49, &a_3};	/* FS-ADDRESS */
static cob_field f_23	= {109, b_23, &a_3};	/* FILE1 Record */
static cob_field f_24	= {32, b_24, &a_4};	/* WS-MODULE */
static cob_field f_26	= {20, b_24 + 12, &a_3};	/* WS-OP */
static cob_field f_27	= {1, b_27, &a_3};	/* WS-CHOICE */
static cob_field f_33	= {2, b_33, &a_6};	/* FS-STAT */
static cob_field f_37	= {1, b_37, &a_3};	/* WS-ERROR */
static cob_field f_39	= {3, b_39, &a_2};	/* WS_NUMR */
static cob_field f_40	= {3, b_40, &a_2};	/* WS-NUMC012 */
static cob_field f_41	= {1, b_41, &a_10};	/* BACK-COLOR */
static cob_field f_42	= {1, b_42, &a_10};	/* FRONT-COLOR */
static cob_field f_43	= {30, b_43, &a_3};	/* WS-STATUS */
static cob_field f_44	= {80, b_44, &a_3};	/* WS-ERRMSG */
static cob_field f_197	= {64, b_197, &a_4};	/* SS-CLS */
static cob_field f_199	= {0, b_197, &a_3};	/* Implicit FILLER */
static cob_field f_200	= {0, b_197 + 1, &a_3};	/* Implicit FILLER */
static cob_field f_201	= {0, b_197 + 2, &a_3};	/* Implicit FILLER */
static cob_field f_203	= {31, b_197 + 3, &a_3};	/* Implicit FILLER */
static cob_field f_204	= {30, b_197 + 34, &a_4};	/* SS-STATUS */
static cob_field f_205	= {30, b_197 + 34, &a_3};	/* Implicit FILLER */
static cob_field f_206	= {59, b_206, &a_4};	/* SS-MENU */
static cob_field f_207	= {11, b_206, &a_3};	/* Implicit FILLER */
static cob_field f_208	= {11, b_206 + 11, &a_3};	/* Implicit FILLER */
static cob_field f_209	= {10, b_206 + 22, &a_3};	/* Implicit FILLER */
static cob_field f_210	= {10, b_206 + 32, &a_3};	/* Implicit FILLER */
static cob_field f_211	= {8, b_206 + 42, &a_3};	/* Implicit FILLER */
static cob_field f_212	= {8, b_206 + 50, &a_3};	/* Implicit FILLER */
static cob_field f_213	= {1, b_206 + 58, &a_3};	/* Implicit FILLER */
static cob_field f_214	= {113, b_214, &a_4};	/* SS-RECORD-SCREEN */
static cob_field f_215	= {17, b_214, &a_4};	/* SS-KEY */
static cob_field f_216	= {8, b_214, &a_3};	/* Implicit FILLER */
static cob_field f_217	= {9, b_214 + 8, &a_7};	/* Implicit FILLER */
static cob_field f_218	= {96, b_214 + 17, &a_4};	/* SS-DATA */
static cob_field f_219	= {8, b_214 + 17, &a_3};	/* Implicit FILLER */
static cob_field f_220	= {40, b_214 + 25, &a_3};	/* Implicit FILLER */
static cob_field f_221	= {8, b_214 + 65, &a_3};	/* Implicit FILLER */
static cob_field f_222	= {40, b_214 + 73, &a_3};	/* Implicit FILLER */
static cob_field f_223	= {81, b_223, &a_4};	/* SS-ERROR */
static cob_field f_225	= {80, b_223, &a_3};	/* Implicit FILLER */
static cob_field f_226	= {1, b_223 + 80, &a_3};	/* Implicit FILLER */
static cob_field f_227	= {4, b_227, &a_8};	/* COB-CRT-STATUS */

/* End of fields */

