/* Generated by           cobc 3.2.0 */
/* Generated from         customer.cob */
/* Generated at           set 13 2023 12:16:59 */
/* GnuCOBOL build date    Jul 28 2023 19:10:09 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -g -fsource-location -ftraceall -Q --coverage -A --coverage -v -O0 -x customer.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Picture strings */

static const cob_pic_symbol p_1[] = {
	{'9', 9},
	{'\0', 1}
};


/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x10,   3,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_5 =	{0x10,   1,   0, 0x0007, NULL};
static const cob_field_attr a_6 =	{0x10,   2,   0, 0x0000, NULL};
static const cob_field_attr a_7 =	{0x24,   9,   0, 0x0008, p_1};
static const cob_field_attr a_8 =	{0x10,   4,   0, 0x0000, NULL};
static const cob_field_attr a_9 =	{0x10,   2,   0, 0x1000, NULL};
static const cob_field_attr a_10 =	{0x10,   1,   0, 0x0000, NULL};
static const cob_field_attr a_11 =	{0x10,   1,   0, 0x1000, NULL};

static const cob_field_attr cob_all_attr = {0x22, 0, 0, 0, NULL};


/* Constants */
static const cob_field c_1	= {21, (cob_u8_ptr)"COB_SCREEN_EXCEPTIONS", &a_1};
static const cob_field c_2	= {1, (cob_u8_ptr)"Y", &a_1};
static const cob_field c_3	= {14, (cob_u8_ptr)"COB_SCREEN_ESC", &a_1};
static const cob_field c_4	= {8, (cob_u8_ptr)"ESCDELAY", &a_1};
static const cob_field c_5	= {2, (cob_u8_ptr)"25", &a_1};
static const cob_field c_6	= {4, (cob_u8_ptr)"MENU", &a_1};
static const cob_field c_7	= {2, (cob_u8_ptr)"+1", &a_5};
static const cob_field c_8	= {11, (cob_u8_ptr)"ESC TO EXIT", &a_1};
static const cob_field c_9	= {31, (cob_u8_ptr)"PLEASE PROVIDE NAME AND ADDRESS", &a_1};
static const cob_field c_10	= {23, (cob_u8_ptr)"CUSTOMER ALREADY EXISTS", &a_1};
static const cob_field c_11	= {11, (cob_u8_ptr)"PRESS ENTER", &a_1};
static const cob_field c_12	= {20, (cob_u8_ptr)"ERROR WRITING RECORD", &a_1};
static const cob_field c_13	= {32, (cob_u8_ptr)"CONFIRM CUSTOMER DELETION (Y/N)\?", &a_1};
static const cob_field c_14	= {21, (cob_u8_ptr)"ERROR DELETING RECORD", &a_1};
static const cob_field c_15	= {18, (cob_u8_ptr)"CUSTOMER NOT FOUND", &a_1};
static const cob_field c_16	= {13, (cob_u8_ptr)"customers.dat", &a_1};
static const cob_field c_17	= {2, (cob_u8_ptr)"01", &a_9};
static const cob_field c_18	= {2, (cob_u8_ptr)"02", &a_9};
static const cob_field c_19	= {1, (cob_u8_ptr)"2", &a_11};
static const cob_field c_20	= {1, (cob_u8_ptr)"6", &a_11};
static const cob_field c_21	= {2, (cob_u8_ptr)"07", &a_9};
static const cob_field c_22	= {2, (cob_u8_ptr)"15", &a_9};
static const cob_field c_23	= {2, (cob_u8_ptr)"08", &a_9};
static const cob_field c_24	= {2, (cob_u8_ptr)"09", &a_9};
static const cob_field c_25	= {2, (cob_u8_ptr)"10", &a_9};
static const cob_field c_26	= {2, (cob_u8_ptr)"11", &a_9};
static const cob_field c_27	= {2, (cob_u8_ptr)"13", &a_9};
static const cob_field c_28	= {1, (cob_u8_ptr)"1", &a_11};
static const cob_field c_29	= {2, (cob_u8_ptr)"12", &a_9};
static const cob_field c_30	= {1, (cob_u8_ptr)"4", &a_11};

static cob_field cob_all_zero	= {1, (cob_u8_ptr)"0", &cob_all_attr};


/* Strings */
static const char st_1[]	= "CUSTOMERS";
static const char st_2[]	= "001-START";
static const char st_3[]	= "001-FINISH";
static const char st_4[]	= "002-INCLUDE";
static const char st_5[]	= "002-INCLUDE-LOOP";
static const char st_6[]	= "002-INCLUDE-END";
static const char st_7[]	= "003-CONSULT";
static const char st_8[]	= "003-CONSULT-LOOP";
static const char st_9[]	= "003-CONSULT-END";
static const char st_10[]	= "004-UPDATE";
static const char st_11[]	= "004-UPDATE-LOOP";
static const char st_12[]	= "004-UPDATE-END";
static const char st_13[]	= "005-DELETE";
static const char st_14[]	= "005-DELETE-END";
static const char st_15[]	= "006-READ-CUSTOMER";
static const char st_16[]	= "006-READ-CUSTOMER-END";
static const char st_17[]	= "007-OPEN-FILES";
static const char st_18[]	= "008-SHOW-ERROR";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"customer.cob"};

#define COB_SET_SCREEN(s,typ,att,nxt,prv,chld,p,fld,val,l,c,fg,bg,prmpt,occ) \
do{	s.next = nxt;     \
	s.prev = prv;     \
	s.child = chld;   \
	s.parent = p;     \
	s.field = fld;    \
	s.value = val;    \
	s.line = l;       \
	s.column = c;     \
	s.foreg = fg;     \
	s.backg = bg;     \
	s.prompt = prmpt; \
	s.type = typ;     \
	s.occurs = occ;   \
	s.attr = att;     \
} ONCE_COB


#define cob_nop	if (!module) cob_nop

