/* Generated by           cobc 3.3-dev.0 */
/* Generated from         datatypes.cob */
/* Generated at           dez 27 2023 23:51:17 */
/* GnuCOBOL build date    Dec 26 2023 19:54:15 */
/* GnuCOBOL package date  Aug 22 2023 07:38:54 UTC */
/* Compile command        cobc -g -fsource-location -ftraceall -v -O0 -x datatypes.cob */

/* Program local variables for 'datatypes' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_17[99] __attribute__((aligned));	/* numeric-data */
static cob_u8_t	b_45[5] __attribute__((aligned));	/* duma */
static cob_u8_t	b_46[12] __attribute__((aligned));	/* floating-data */
static cob_u8_t	b_49[17] __attribute__((aligned));	/* special-data */
static cob_u8_t	b_55[101] __attribute__((aligned));	/* alphanumeric-data */
static cob_u8_t	b_62[160] __attribute__((aligned));	/* national-data */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17	= {99, b_17, &a_38};	/* numeric-data */
static cob_field f_18	= {3, b_17, &a_14};	/* dispd1 */
static cob_field f_19	= {3, b_17 + 3, &a_14};	/* dispd2 */
static cob_field f_20	= {5, b_17 + 6, &a_7};	/* disp1 */
static cob_field f_21	= {5, b_17 + 11, &a_15};	/* disp-u */
static cob_field f_22	= {4, b_17 + 16, &a_10};	/* dispp */
static cob_field f_23	= {4, b_17 + 20, &a_11};	/* dispp-u */
static cob_field f_24	= {4, b_17 + 24, &a_12};	/* disppp */
static cob_field f_25	= {4, b_17 + 28, &a_13};	/* disppp-u */
static cob_field f_26	= {4, b_17 + 32, &a_8};	/* bin */
static cob_field f_27	= {4, b_17 + 36, &a_9};	/* bin-u */
static cob_field f_28	= {3, b_17 + 40, &a_16};	/* cmp3 */
static cob_field f_29	= {3, b_17 + 43, &a_17};	/* cmp3-u */
static cob_field f_30	= {4, b_17 + 46, &a_2};	/* cmp5 */
static cob_field f_31	= {4, b_17 + 50, &a_18};	/* cmp5-u */
static cob_field f_32	= {3, b_17 + 54, &a_19};	/* cmp6 */
static cob_field f_33	= {3, b_17 + 57, &a_20};	/* cmpx */
static cob_field f_34	= {3, b_17 + 60, &a_21};	/* cmpx-u */
static cob_field f_35	= {3, b_17 + 63, &a_20};	/* cmpn */
static cob_field f_36	= {3, b_17 + 66, &a_21};	/* cmpn-u */
static cob_field f_37	= {1, b_17 + 69, &a_22};	/* chr */
static cob_field f_38	= {1, b_17 + 70, &a_23};	/* chr-u */
static cob_field f_39	= {2, b_17 + 71, &a_24};	/* shrt */
static cob_field f_40	= {2, b_17 + 73, &a_25};	/* shrt-u */
static cob_field f_41	= {4, b_17 + 75, &a_26};	/* long */
static cob_field f_42	= {4, b_17 + 79, &a_27};	/* long-u */
static cob_field f_43	= {8, b_17 + 83, &a_28};	/* dble */
static cob_field f_44	= {8, b_17 + 91, &a_29};	/* dble-u */
static cob_field f_45	= {5, b_45, &a_7};	/* duma */
static cob_field f_46	= {12, b_46, &a_38};	/* floating-data */
static cob_field f_47	= {8, b_46, &a_30};	/* dbl */
static cob_field f_48	= {4, b_46 + 8, &a_31};	/* flt */
static cob_field f_49	= {17, b_49, &a_38};	/* special-data */
static cob_field f_50	= {1, b_49, &a_32};	/* r2d2 */
static cob_field f_51	= {4, b_49 + 1, &a_33};	/* point */
static cob_field f_52	= {4, b_49 + 5, &a_33};	/* ppoint */
static cob_field f_53	= {4, b_49 + 9, &a_34};	/* idx */
static cob_field f_54	= {4, b_49 + 13, &a_35};	/* hnd */
static cob_field f_55	= {101, b_55, &a_38};	/* alphanumeric-data */
static cob_field f_56	= {36, b_55, &a_36};	/* alpnum */
static cob_field f_57	= {36, b_55 + 36, &a_36};	/* alpha */
static cob_field f_58	= {7, b_55 + 72, &a_3};	/* edit-num1 */
static cob_field f_59	= {7, b_55 + 79, &a_4};	/* edit-num2 */
static cob_field f_60	= {7, b_55 + 86, &a_5};	/* edit-num3 */
static cob_field f_61	= {8, b_55 + 93, &a_6};	/* edit-num4 */
static cob_field f_62	= {160, b_62, &a_38};	/* national-data */
static cob_field f_63	= {72, b_62, &a_37};	/* nat */
static cob_field f_65	= {14, b_62 + 102, &a_3};	/* net-num1 */
static cob_field f_66	= {14, b_62 + 116, &a_4};	/* net-num2 */
static cob_field f_67	= {14, b_62 + 130, &a_5};	/* net-num3 */
static cob_field f_68	= {16, b_62 + 144, &a_6};	/* net-num4 */

/* End of fields */

