/* Generated by           cobc 3.3-dev.0 */
/* Generated from         datatypes.cob */
/* Generated at           dez 27 2023 23:51:17 */
/* GnuCOBOL build date    Dec 26 2023 19:54:15 */
/* GnuCOBOL package date  Aug 22 2023 07:38:54 UTC */
/* Compile command        cobc -g -fsource-location -ftraceall -v -O0 -x datatypes.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"datatypes.cob"
#define  COB_PACKAGE_VERSION		"3.3-dev"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"dez 27 2023 23:51:17"
#define  COB_MODULE_DATE		20231227
#define  COB_MODULE_TIME		235117

/* Global variables */
#include "datatypes.c.h"

/* Function prototypes */

static int		datatypes ();
static int		datatypes_ (const int);
static void		datatypes_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (datatypes ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'datatypes' */

/* ENTRY 'datatypes' */

static int
datatypes ()
{
  return datatypes_ (0);
}

static int
datatypes_ (const int entry)
{
  /* Program local variables */
  #include "datatypes.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 69        : Entry     datatypes               : datatypes.cob */
  l_2:;
#line 69 "datatypes.cob"
  ENTRY_DATATYPES:	module->statement = STMT_ENTRY;
#line 105 "datatypes.c"
  module->module_stmt = 0x00100045;
  cob_trace_entry (st_1);
  module->section_name = NULL;
  module->paragraph_name = NULL;
  cob_trace_sect (NULL);
  cob_trace_para (NULL);

  /* Line: 69        : SET                : datatypes.cob */
#line 69 "datatypes.cob"
  module->statement = STMT_SET;
#line 116 "datatypes.c"
  cob_trace_statement (STMT_SET);
  (*(int *) (b_49 + 9)) = 1;

  /* Line: 70        : SET                : datatypes.cob */
#line 70 "datatypes.cob"
  module->statement = STMT_SET;
#line 123 "datatypes.c"
  module->module_stmt = 0x00100046;
  cob_trace_statement (STMT_SET);
  (*(unsigned char **) (b_49 + 1)) = (b_49 + 5);

  /* Line: 71        : SET                : datatypes.cob */
#line 71 "datatypes.cob"
  module->statement = STMT_SET;
#line 131 "datatypes.c"
  module->module_stmt = 0x00100047;
  cob_trace_statement (STMT_SET);
  (*(unsigned char **) (b_49 + 5)) = cob_call_field ((cob_field *)&c_1, NULL, 0, 0);

  /* Line: 72        : MOVE               : datatypes.cob */
#line 72 "datatypes.cob"
  module->statement = STMT_MOVE;
#line 139 "datatypes.c"
  module->module_stmt = 0x00100048;
  cob_trace_statement (STMT_MOVE);
  cob_move (&f_30, &f_58);
  cob_move (&f_30, &f_59);
  cob_move (&f_30, &f_60);
  cob_move (&f_30, &f_61);

  /* Line: 73        : MOVE               : datatypes.cob */
#line 73 "datatypes.cob"
  module->statement = STMT_MOVE;
#line 150 "datatypes.c"
  module->module_stmt = 0x00100049;
  cob_trace_statement (STMT_MOVE);
  cob_move (&f_30, &f_65);
  cob_move (&f_30, &f_66);
  cob_move (&f_30, &f_67);
  cob_move (&f_30, &f_68);

  /* Line: 75        : DISPLAY            : datatypes.cob */
#line 75 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 161 "datatypes.c"
  module->module_stmt = 0x0010004B;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_45);

  /* Line: 76        : DISPLAY            : datatypes.cob */
#line 76 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 169 "datatypes.c"
  module->module_stmt = 0x0010004C;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_26);

  /* Line: 77        : DISPLAY            : datatypes.cob */
#line 77 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 177 "datatypes.c"
  module->module_stmt = 0x0010004D;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_27);

  /* Line: 78        : DISPLAY            : datatypes.cob */
#line 78 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 185 "datatypes.c"
  module->module_stmt = 0x0010004E;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_22);

  /* Line: 79        : DISPLAY            : datatypes.cob */
#line 79 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 193 "datatypes.c"
  module->module_stmt = 0x0010004F;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_23);

  /* Line: 80        : DISPLAY            : datatypes.cob */
#line 80 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 201 "datatypes.c"
  module->module_stmt = 0x00100050;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_24);

  /* Line: 81        : DISPLAY            : datatypes.cob */
#line 81 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 209 "datatypes.c"
  module->module_stmt = 0x00100051;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_25);

  /* Line: 82        : DISPLAY            : datatypes.cob */
#line 82 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 217 "datatypes.c"
  module->module_stmt = 0x00100052;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_18);

  /* Line: 83        : DISPLAY            : datatypes.cob */
#line 83 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 225 "datatypes.c"
  module->module_stmt = 0x00100053;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_19);

  /* Line: 84        : DISPLAY            : datatypes.cob */
#line 84 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 233 "datatypes.c"
  module->module_stmt = 0x00100054;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_20);

  /* Line: 85        : DISPLAY            : datatypes.cob */
#line 85 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 241 "datatypes.c"
  module->module_stmt = 0x00100055;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_21);

  /* Line: 86        : DISPLAY            : datatypes.cob */
#line 86 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 249 "datatypes.c"
  module->module_stmt = 0x00100056;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_28);

  /* Line: 87        : DISPLAY            : datatypes.cob */
#line 87 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 257 "datatypes.c"
  module->module_stmt = 0x00100057;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_29);

  /* Line: 88        : DISPLAY            : datatypes.cob */
#line 88 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 265 "datatypes.c"
  module->module_stmt = 0x00100058;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_30);

  /* Line: 89        : DISPLAY            : datatypes.cob */
#line 89 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 273 "datatypes.c"
  module->module_stmt = 0x00100059;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_31);

  /* Line: 90        : DISPLAY            : datatypes.cob */
#line 90 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 281 "datatypes.c"
  module->module_stmt = 0x0010005A;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_32);

  /* Line: 91        : DISPLAY            : datatypes.cob */
#line 91 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 289 "datatypes.c"
  module->module_stmt = 0x0010005B;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_33);

  /* Line: 92        : DISPLAY            : datatypes.cob */
#line 92 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 297 "datatypes.c"
  module->module_stmt = 0x0010005C;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_34);

  /* Line: 93        : DISPLAY            : datatypes.cob */
#line 93 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 305 "datatypes.c"
  module->module_stmt = 0x0010005D;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_35);

  /* Line: 94        : DISPLAY            : datatypes.cob */
#line 94 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 313 "datatypes.c"
  module->module_stmt = 0x0010005E;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_36);

  /* Line: 95        : DISPLAY            : datatypes.cob */
#line 95 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 321 "datatypes.c"
  module->module_stmt = 0x0010005F;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_37);

  /* Line: 96        : DISPLAY            : datatypes.cob */
#line 96 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 329 "datatypes.c"
  module->module_stmt = 0x00100060;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_38);

  /* Line: 97        : DISPLAY            : datatypes.cob */
#line 97 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 337 "datatypes.c"
  module->module_stmt = 0x00100061;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_39);

  /* Line: 98        : DISPLAY            : datatypes.cob */
#line 98 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 345 "datatypes.c"
  module->module_stmt = 0x00100062;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_40);

  /* Line: 99        : DISPLAY            : datatypes.cob */
#line 99 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 353 "datatypes.c"
  module->module_stmt = 0x00100063;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_41);

  /* Line: 100       : DISPLAY            : datatypes.cob */
#line 100 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 361 "datatypes.c"
  module->module_stmt = 0x00100064;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_42);

  /* Line: 101       : DISPLAY            : datatypes.cob */
#line 101 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 369 "datatypes.c"
  module->module_stmt = 0x00100065;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_43);

  /* Line: 102       : DISPLAY            : datatypes.cob */
#line 102 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 377 "datatypes.c"
  module->module_stmt = 0x00100066;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_44);

  /* Line: 103       : DISPLAY            : datatypes.cob */
#line 103 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 385 "datatypes.c"
  module->module_stmt = 0x00100067;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_47);

  /* Line: 104       : DISPLAY            : datatypes.cob */
#line 104 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 393 "datatypes.c"
  module->module_stmt = 0x00100068;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_48);

  /* Line: 105       : DISPLAY            : datatypes.cob */
#line 105 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 401 "datatypes.c"
  module->module_stmt = 0x00100069;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_50);

  /* Line: 106       : DISPLAY            : datatypes.cob */
#line 106 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 409 "datatypes.c"
  module->module_stmt = 0x0010006A;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_51);

  /* Line: 107       : DISPLAY            : datatypes.cob */
#line 107 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 417 "datatypes.c"
  module->module_stmt = 0x0010006B;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_52);

  /* Line: 108       : DISPLAY            : datatypes.cob */
#line 108 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 425 "datatypes.c"
  module->module_stmt = 0x0010006C;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_53);

  /* Line: 109       : DISPLAY            : datatypes.cob */
#line 109 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 433 "datatypes.c"
  module->module_stmt = 0x0010006D;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_54);

  /* Line: 110       : DISPLAY            : datatypes.cob */
#line 110 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 441 "datatypes.c"
  module->module_stmt = 0x0010006E;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_56);

  /* Line: 111       : DISPLAY            : datatypes.cob */
#line 111 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 449 "datatypes.c"
  module->module_stmt = 0x0010006F;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_57);

  /* Line: 112       : DISPLAY            : datatypes.cob */
#line 112 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 457 "datatypes.c"
  module->module_stmt = 0x00100070;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_58);

  /* Line: 113       : DISPLAY            : datatypes.cob */
#line 113 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 465 "datatypes.c"
  module->module_stmt = 0x00100071;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_59);

  /* Line: 114       : DISPLAY            : datatypes.cob */
#line 114 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 473 "datatypes.c"
  module->module_stmt = 0x00100072;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_60);

  /* Line: 115       : DISPLAY            : datatypes.cob */
#line 115 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 481 "datatypes.c"
  module->module_stmt = 0x00100073;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_61);

  /* Line: 116       : DISPLAY            : datatypes.cob */
#line 116 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 489 "datatypes.c"
  module->module_stmt = 0x00100074;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_63);

  /* Line: 117       : DISPLAY            : datatypes.cob */
#line 117 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 497 "datatypes.c"
  module->module_stmt = 0x00100075;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_65);

  /* Line: 118       : DISPLAY            : datatypes.cob */
#line 118 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 505 "datatypes.c"
  module->module_stmt = 0x00100076;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_66);

  /* Line: 119       : DISPLAY            : datatypes.cob */
#line 119 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 513 "datatypes.c"
  module->module_stmt = 0x00100077;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_67);

  /* Line: 120       : DISPLAY            : datatypes.cob */
#line 120 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 521 "datatypes.c"
  module->module_stmt = 0x00100078;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_68);

  /* Line: 122       : DISPLAY            : datatypes.cob */
#line 122 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 529 "datatypes.c"
  module->module_stmt = 0x0010007A;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_17);

  /* Line: 123       : DISPLAY            : datatypes.cob */
#line 123 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 537 "datatypes.c"
  module->module_stmt = 0x0010007B;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_46);

  /* Line: 124       : DISPLAY            : datatypes.cob */
#line 124 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 545 "datatypes.c"
  module->module_stmt = 0x0010007C;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_49);

  /* Line: 125       : DISPLAY            : datatypes.cob */
#line 125 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 553 "datatypes.c"
  module->module_stmt = 0x0010007D;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_55);

  /* Line: 126       : DISPLAY            : datatypes.cob */
#line 126 "datatypes.cob"
  module->statement = STMT_DISPLAY;
#line 561 "datatypes.c"
  module->module_stmt = 0x0010007E;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_62);

  /* Line: 128       : GOBACK             : datatypes.cob */
#line 128 "datatypes.cob"
  module->statement = STMT_GOBACK;
#line 569 "datatypes.c"
  module->module_stmt = 0x00100080;
  cob_trace_statement (STMT_GOBACK);
  goto exit_program;

  /* Line: 129       : last source line                  :datatypes.cob */
#line 129 "datatypes.cob"
  module->module_stmt = 0x00100081;
#line 577 "datatypes.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Trace program exit */
  cob_trace_exit (st_1);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  datatypes_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field dispd1 */
#line 7 "datatypes.cob"
  cob_nop ();
#line 634 "datatypes.c"
  memcpy (b_17, "51p", 3);
  /* initialize field dispd2 */
#line 8 "datatypes.cob"
  cob_nop ();
#line 639 "datatypes.c"
  memcpy (b_17 + 3, "510", 3);
  /* initialize field disp1 */
#line 9 "datatypes.cob"
  cob_nop ();
#line 644 "datatypes.c"
  cob_move ((cob_field *)&c_2, &f_20);
  /* initialize field disp-u */
#line 10 "datatypes.cob"
  cob_nop ();
#line 649 "datatypes.c"
  cob_move ((cob_field *)&c_3, &f_21);
  /* initialize field dispp */
#line 11 "datatypes.cob"
  cob_nop ();
#line 654 "datatypes.c"
  cob_move ((cob_field *)&c_4, &f_22);
  /* initialize field dispp-u */
#line 12 "datatypes.cob"
  cob_nop ();
#line 659 "datatypes.c"
  cob_move ((cob_field *)&c_5, &f_23);
  /* initialize field disppp */
#line 13 "datatypes.cob"
  cob_nop ();
#line 664 "datatypes.c"
  cob_move ((cob_field *)&c_6, &f_24);
  /* initialize field disppp-u */
#line 14 "datatypes.cob"
  cob_nop ();
#line 669 "datatypes.c"
  cob_move ((cob_field *)&c_7, &f_25);
  /* initialize field bin */
#line 15 "datatypes.cob"
  cob_nop ();
#line 674 "datatypes.c"
  cob_move ((cob_field *)&c_2, &f_26);
  /* initialize field bin-u */
#line 16 "datatypes.cob"
  cob_nop ();
#line 679 "datatypes.c"
  cob_move ((cob_field *)&c_3, &f_27);
  /* initialize field cmp3 */
#line 17 "datatypes.cob"
  cob_nop ();
#line 684 "datatypes.c"
  cob_move ((cob_field *)&c_2, &f_28);
  /* initialize field cmp3-u */
#line 18 "datatypes.cob"
  cob_nop ();
#line 689 "datatypes.c"
  cob_move ((cob_field *)&c_3, &f_29);
  /* initialize field cmp5 */
#line 19 "datatypes.cob"
  cob_nop ();
#line 694 "datatypes.c"
  cob_move ((cob_field *)&c_2, &f_30);
  /* initialize field cmp5-u */
#line 20 "datatypes.cob"
  cob_nop ();
#line 699 "datatypes.c"
  cob_move ((cob_field *)&c_3, &f_31);
  /* initialize field cmp6 */
#line 21 "datatypes.cob"
  cob_nop ();
#line 704 "datatypes.c"
  cob_move ((cob_field *)&c_3, &f_32);
  /* initialize field cmpx */
#line 22 "datatypes.cob"
  cob_nop ();
#line 709 "datatypes.c"
  cob_move ((cob_field *)&c_2, &f_33);
  /* initialize field cmpx-u */
#line 23 "datatypes.cob"
  cob_nop ();
#line 714 "datatypes.c"
  cob_move ((cob_field *)&c_3, &f_34);
  /* initialize field cmpn */
#line 24 "datatypes.cob"
  cob_nop ();
#line 719 "datatypes.c"
  cob_move ((cob_field *)&c_2, &f_35);
  /* initialize field cmpn-u */
#line 25 "datatypes.cob"
  cob_nop ();
#line 724 "datatypes.c"
  cob_move ((cob_field *)&c_3, &f_36);
  /* initialize field chr */
#line 26 "datatypes.cob"
  cob_nop ();
#line 729 "datatypes.c"
  cob_move ((cob_field *)&c_8, &f_37);
  /* initialize field chr-u */
#line 27 "datatypes.cob"
  cob_nop ();
#line 734 "datatypes.c"
  cob_move ((cob_field *)&c_9, &f_38);
  /* initialize field shrt */
#line 28 "datatypes.cob"
  cob_nop ();
#line 739 "datatypes.c"
  cob_move ((cob_field *)&c_10, &f_39);
  /* initialize field shrt-u */
#line 29 "datatypes.cob"
  cob_nop ();
#line 744 "datatypes.c"
  cob_move ((cob_field *)&c_11, &f_40);
  /* initialize field long */
#line 30 "datatypes.cob"
  cob_nop ();
#line 749 "datatypes.c"
  cob_move ((cob_field *)&c_12, &f_41);
  /* initialize field long-u */
#line 31 "datatypes.cob"
  cob_nop ();
#line 754 "datatypes.c"
  cob_move ((cob_field *)&c_13, &f_42);
  /* initialize field dble */
#line 32 "datatypes.cob"
  cob_nop ();
#line 759 "datatypes.c"
  cob_move ((cob_field *)&c_14, &f_43);
  /* initialize field dble-u */
#line 33 "datatypes.cob"
  cob_nop ();
#line 764 "datatypes.c"
  cob_move ((cob_field *)&c_15, &f_44);

  /* initialize field duma */
#line 35 "datatypes.cob"
  cob_nop ();
#line 770 "datatypes.c"
  cob_move ((cob_field *)&c_2, &f_45);

  /* initialize field dbl */
#line 37 "datatypes.cob"
  cob_nop ();
#line 776 "datatypes.c"
  cob_move ((cob_field *)&c_16, &f_47);
  /* initialize field flt */
#line 38 "datatypes.cob"
  cob_nop ();
#line 781 "datatypes.c"
  cob_move ((cob_field *)&c_17, &f_48);

  /* initialize field r2d2 */
#line 49 "datatypes.cob"
  cob_nop ();
#line 787 "datatypes.c"
  cob_move ((cob_field *)&c_18, &f_50);
  /* initialize field point */
#line 50 "datatypes.cob"
  cob_nop ();
#line 792 "datatypes.c"
  memset (b_49 + 1, 0x0, 16);

  /* initialize field alpnum */
#line 55 "datatypes.cob"
  cob_nop ();
#line 798 "datatypes.c"
  memcpy (b_55, "some numb3rs 4 n00bs l1k3 m3        ", 36);
  /* initialize field alpha */
#line 56 "datatypes.cob"
  cob_nop ();
#line 803 "datatypes.c"
  memcpy (b_55 + 36, "thats some text                     ", 36);
  /* initialize field edit-num1 */
#line 57 "datatypes.cob"
  cob_nop ();
#line 808 "datatypes.c"
  cob_move (&cob_all_zero, &f_58);
  /* initialize field edit-num2 */
#line 58 "datatypes.cob"
  cob_nop ();
#line 813 "datatypes.c"
  cob_move (&cob_all_zero, &f_59);
  /* initialize field edit-num3 */
#line 59 "datatypes.cob"
  cob_nop ();
#line 818 "datatypes.c"
  cob_move (&cob_all_zero, &f_60);
  /* initialize field edit-num4 */
#line 60 "datatypes.cob"
  cob_nop ();
#line 823 "datatypes.c"
  cob_move (&cob_all_zero, &f_61);

  /* initialize field nat */
#line 62 "datatypes.cob"
  cob_nop ();
#line 829 "datatypes.c"
  memcpy (b_62, "data shown here will change.                                            ", 72);
  /* initialize field nat-num */
#line 63 "datatypes.cob"
  cob_nop ();
#line 834 "datatypes.c"
  memset (b_62 + 72, (unsigned char)'0', 30);
  /* initialize field net-num1 */
#line 64 "datatypes.cob"
  cob_nop ();
#line 839 "datatypes.c"
  cob_move (&cob_all_zero, &f_65);
  /* initialize field net-num2 */
#line 65 "datatypes.cob"
  cob_nop ();
#line 844 "datatypes.c"
  cob_move (&cob_all_zero, &f_66);
  /* initialize field net-num3 */
#line 66 "datatypes.cob"
  cob_nop ();
#line 849 "datatypes.c"
  cob_move (&cob_all_zero, &f_67);
  /* initialize field net-num4 */
#line 67 "datatypes.cob"
  cob_nop ();
#line 854 "datatypes.c"
  cob_move (&cob_all_zero, &f_68);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'datatypes' */

/* Initialize module structure for datatypes */
static void datatypes_module_init (cob_module *module)
{
  module->module_name = "datatypes";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())datatypes;
  module->module_cancel.funcptr = (void *(*)())datatypes_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 6;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

