/* Generated by           cobc 3.2.0 */
/* Generated from         number.cob */
/* Generated at           set 13 2023 10:51:01 */
/* GnuCOBOL build date    Jul 28 2023 19:10:09 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -g -fsource-location -ftraceall -Q --coverage -A --coverage -v -O0 -x number.cob */

/* Program local variables for 'GCACCEPT9' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_26[1] __attribute__((aligned));	/* pro */
static cob_u8_t	b_27[4] __attribute__((aligned));	/* wKeyPressed */
static cob_u8_t	b_28[4] __attribute__((aligned));	/* wRetCode */
static cob_u8_t	b_29[9] __attribute__((aligned));	/* Field9 */
static cob_u8_t	b_30[11] __attribute__((aligned));	/* FieldX */
static cob_u8_t	b_31[11] __attribute__((aligned));	/* FieldZ */

/* End of local data storage */


/* Fields (local) */
static cob_field f_26	= {1, b_26, &a_4};	/* pro */
static cob_field f_27	= {4, b_27, &a_5};	/* wKeyPressed */
static cob_field f_28	= {4, b_28, &a_5};	/* wRetCode */
static cob_field f_29	= {9, b_29, &a_6};	/* Field9 */
static cob_field f_30	= {11, b_30, &a_4};	/* FieldX */
static cob_field f_31	= {11, b_31, &a_7};	/* FieldZ */

/* End of fields */

