/* Generated by           cobc 3.2.0 */
/* Generated from         number.cob */
/* Generated at           set 13 2023 10:51:01 */
/* GnuCOBOL build date    Jul 28 2023 19:10:09 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -g -fsource-location -ftraceall -Q --coverage -A --coverage -v -O0 -x number.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Picture strings */

static const cob_pic_symbol p_1[] = {
	{'-', 7},
	{'9', 1},
	{',', 1},
	{'9', 2},
	{'\0', 1}
};


/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x10,   4,   0, 0x1000, NULL};
static const cob_field_attr a_3 =	{0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_4 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_5 =	{0x10,   4,   0, 0x0000, NULL};
static const cob_field_attr a_6 =	{0x10,   9,   2, 0x0001, NULL};
static const cob_field_attr a_7 =	{0x24,   9,   2, 0x0001, p_1};

static const cob_field_attr cob_all_attr = {0x22, 0, 0, 0, NULL};


/* Constants */
static const cob_field c_1	= {21, (cob_u8_ptr)"COB_SCREEN_EXCEPTIONS", &a_1};
static const cob_field c_2	= {1, (cob_u8_ptr)"Y", &a_1};
static const cob_field c_3	= {14, (cob_u8_ptr)"COB_SCREEN_ESC", &a_1};
static const cob_field c_4	= {47, (cob_u8_ptr)"GnuCOBOL - HOW TO MANAGE NUMERIC DATA ON SCREEN", &a_1};
static const cob_field c_5	= {4, (cob_u8_ptr)"0205", &a_2};
static const cob_field c_6	= {1, (cob_u8_ptr)"1", &a_3};
static const cob_field c_7	= {1, (cob_u8_ptr)"7", &a_3};
static const cob_field c_8	= {47, (cob_u8_ptr)"-----------------------------------------------", &a_1};
static const cob_field c_9	= {4, (cob_u8_ptr)"0305", &a_2};
static const cob_field c_10	= {21, (cob_u8_ptr)"Type an amount .....:", &a_1};
static const cob_field c_11	= {4, (cob_u8_ptr)"0505", &a_2};
static const cob_field c_12	= {22, (cob_u8_ptr)"signed with 2 decimals", &a_1};
static const cob_field c_13	= {4, (cob_u8_ptr)"0540", &a_2};
static const cob_field c_14	= {11, (cob_u8_ptr)"12345678901", &a_1};
static const cob_field c_15	= {4, (cob_u8_ptr)"0627", &a_2};
static const cob_field c_16	= {24, (cob_u8_ptr)"(decimal point is comma)", &a_1};
static const cob_field c_17	= {4, (cob_u8_ptr)"0640", &a_2};
static const cob_field c_18	= {10, (cob_u8_ptr)"ESC = EXIT", &a_1};
static const cob_field c_19	= {4, (cob_u8_ptr)"2305", &a_2};
static const cob_field c_20	= {4, (cob_u8_ptr)"0527", &a_2};
static const cob_field c_21	= {1, (cob_u8_ptr)"3", &a_3};
static const cob_field c_22	= {21, (cob_u8_ptr)"RetCode.............:", &a_1};
static const cob_field c_23	= {4, (cob_u8_ptr)"1305", &a_2};
static const cob_field c_24	= {4, (cob_u8_ptr)"1334", &a_2};
static const cob_field c_25	= {1, (cob_u8_ptr)" ", &a_1};
static const cob_field c_26	= {4, (cob_u8_ptr)"1505", &a_2};
static const cob_field c_27	= {1, (cob_u8_ptr)"0", &a_3};
static const cob_field c_28	= {22, (cob_u8_ptr)"correct format number ", &a_1};
static const cob_field c_29	= {1, (cob_u8_ptr)"2", &a_3};
static const cob_field c_30	= {32, (cob_u8_ptr)"=> empty field ! forced to ZERO.", &a_1};
static const cob_field c_31	= {4, (cob_u8_ptr)"1520", &a_2};
static const cob_field c_32	= {1, (cob_u8_ptr)"4", &a_3};
static const cob_field c_33	= {21, (cob_u8_ptr)"Edited Number.......:", &a_1};
static const cob_field c_34	= {4, (cob_u8_ptr)"0905", &a_2};
static const cob_field c_35	= {4, (cob_u8_ptr)"0927", &a_2};
static const cob_field c_36	= {21, (cob_u8_ptr)"Number in memory....:", &a_1};
static const cob_field c_37	= {4, (cob_u8_ptr)"1105", &a_2};
static const cob_field c_38	= {4, (cob_u8_ptr)"1129", &a_2};
static const cob_field c_39	= {38, (cob_u8_ptr)"PIC S9(7)V99 = 9 bytes, 7 int & 2 dec.", &a_1};
static const cob_field c_40	= {4, (cob_u8_ptr)"1140", &a_2};
static const cob_field c_41	= {24, (cob_u8_ptr)"incorrect format number ", &a_1};
static const cob_field c_42	= {35, (cob_u8_ptr)"- 1st wrong character at position: ", &a_1};
static const cob_field c_43	= {4, (cob_u8_ptr)"1529", &a_2};
static const cob_field c_44	= {4, (cob_u8_ptr)"1564", &a_2};

static cob_field cob_all_zero	= {1, (cob_u8_ptr)"0", &cob_all_attr};


/* Strings */
static const char st_1[]	= "GCACCEPT9";
static const char st_2[]	= "Accept-Field";
static const char st_3[]	= "End-Program";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"number.cob"};

#define cob_nop	if (!module) cob_nop

