/* Generated by           cobc 3.2.0 */
/* Generated from         number.cob */
/* Generated at           set 13 2023 10:51:01 */
/* GnuCOBOL build date    Jul 28 2023 19:10:09 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -g -fsource-location -ftraceall -Q --coverage -A --coverage -v -O0 -x number.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"number.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"set 13 2023 10:51:01"
#define  COB_MODULE_DATE		20230913
#define  COB_MODULE_TIME		105101

/* Global variables */
#include "number.c.h"

/* Function prototypes */

static int		GCACCEPT9 ();
static int		GCACCEPT9_ (const int);
static void		GCACCEPT9_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (GCACCEPT9 ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'GCACCEPT9' */

/* ENTRY 'GCACCEPT9' */

static int
GCACCEPT9 ()
{
  return GCACCEPT9_ (0);
}

static int
GCACCEPT9_ (const int entry)
{
  /* Program local variables */
  #include "number.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 54        : Entry     GCACCEPT9               : number.cob */
  l_2:;
#line 54 "number.cob"
  ENTRY_GCACCEPT9:	module->statement = STMT_ENTRY;
#line 105 "number.c"
  module->module_stmt = 0x00100036;
  cob_trace_entry (st_1);
  module->section_name = NULL;
  module->paragraph_name = NULL;
  cob_trace_sect (NULL);
  cob_trace_para (NULL);

  /* Line: 54        : SET                : number.cob */
#line 54 "number.cob"
  module->statement = STMT_SET;
#line 116 "number.c"
  cob_trace_statement (STMT_SET);
  cob_set_environment ((cob_field *)&c_1, (cob_field *)&c_2);

  /* Line: 55        : SET                : number.cob */
#line 55 "number.cob"
  module->statement = STMT_SET;
#line 123 "number.c"
  module->module_stmt = 0x00100037;
  cob_trace_statement (STMT_SET);
  cob_set_environment ((cob_field *)&c_3, (cob_field *)&c_2);

  /* Line: 57        : DISPLAY            : number.cob */
#line 57 "number.cob"
  module->statement = STMT_DISPLAY;
#line 131 "number.c"
  module->module_stmt = 0x00100039;
  cob_trace_statement (STMT_DISPLAY);
  cob_display_field ((cob_field *)&c_4, 32768, "pfb", (cob_field *)&c_5, (cob_field *)&c_6, (cob_field *)&c_7);

  /* Line: 59        : DISPLAY            : number.cob */
#line 59 "number.cob"
  module->statement = STMT_DISPLAY;
#line 139 "number.c"
  module->module_stmt = 0x0010003B;
  cob_trace_statement (STMT_DISPLAY);
  cob_display_field ((cob_field *)&c_8, 32768, "pfb", (cob_field *)&c_9, (cob_field *)&c_6, (cob_field *)&c_7);

  /* Line: 61        : DISPLAY            : number.cob */
#line 61 "number.cob"
  module->statement = STMT_DISPLAY;
#line 147 "number.c"
  module->module_stmt = 0x0010003D;
  cob_trace_statement (STMT_DISPLAY);
  cob_display_field ((cob_field *)&c_10, 32768, "pfb", (cob_field *)&c_11, (cob_field *)&c_6, (cob_field *)&c_7);

  /* Line: 62        : DISPLAY            : number.cob */
#line 62 "number.cob"
  module->statement = STMT_DISPLAY;
#line 155 "number.c"
  module->module_stmt = 0x0010003E;
  cob_trace_statement (STMT_DISPLAY);
  cob_display_field ((cob_field *)&c_12, 32768, "pfb", (cob_field *)&c_13, (cob_field *)&c_6, (cob_field *)&c_7);

  /* Line: 63        : DISPLAY            : number.cob */
#line 63 "number.cob"
  module->statement = STMT_DISPLAY;
#line 163 "number.c"
  module->module_stmt = 0x0010003F;
  cob_trace_statement (STMT_DISPLAY);
  cob_display_field ((cob_field *)&c_14, 32768, "pfb", (cob_field *)&c_15, (cob_field *)&c_6, (cob_field *)&c_7);

  /* Line: 64        : DISPLAY            : number.cob */
#line 64 "number.cob"
  module->statement = STMT_DISPLAY;
#line 171 "number.c"
  module->module_stmt = 0x00100040;
  cob_trace_statement (STMT_DISPLAY);
  cob_display_field ((cob_field *)&c_16, 32768, "pfb", (cob_field *)&c_17, (cob_field *)&c_6, (cob_field *)&c_7);

  /* Line: 65        : DISPLAY            : number.cob */
#line 65 "number.cob"
  module->statement = STMT_DISPLAY;
#line 179 "number.c"
  module->module_stmt = 0x00100041;
  cob_trace_statement (STMT_DISPLAY);
  cob_display_field ((cob_field *)&c_18, 32768, "pfb", (cob_field *)&c_19, (cob_field *)&c_6, (cob_field *)&c_7);

  /* Line: 67        : Paragraph Accept-Field            : number.cob */
  l_5:;
#line 67 "number.cob"
  PARAGRAPH_ACCEPT__FIELD_l_5:	module->statement = STMT_ENTRY;
#line 188 "number.c"
  module->module_stmt = 0x00100043;
  module->paragraph_name = st_2;
  cob_trace_para (st_2);

  /* Line: 68        : ACCEPT             : number.cob */
#line 68 "number.cob"
  module->statement = STMT_ACCEPT;
#line 196 "number.c"
  module->module_stmt = 0x00100044;
  cob_trace_statement (STMT_ACCEPT);
  cob_accept_field (&f_30, 1605648, "pfbP", (cob_field *)&c_20, (cob_field *)&c_21, (cob_field *)&c_6, &f_26);

  /* Line: 72        : IF                 : number.cob */
#line 72 "number.cob"
  module->statement = STMT_IF;
#line 204 "number.c"
  module->module_stmt = 0x00100048;
  cob_trace_statement (STMT_IF);
  if (((int)cob_cmp_numdisp (b_27, 4, 2005LL, 0) == 0))
  {

    /* Line: 72        : GO TO              : number.cob */
#line 72 "number.cob"
    module->statement = STMT_GO_TO;
#line 213 "number.c"
    cob_trace_statement (STMT_GO_TO);
    goto l_6;
  }

  /* Line: 80        : MOVE               : number.cob */
#line 80 "number.cob"
  module->statement = STMT_MOVE;
#line 221 "number.c"
  module->module_stmt = 0x00100050;
  cob_trace_statement (STMT_MOVE);
  cob_move (cob_intr_test_numval (&f_30), &f_28);

  /* Line: 81        : DISPLAY            : number.cob */
#line 81 "number.cob"
  module->statement = STMT_DISPLAY;
#line 229 "number.c"
  module->module_stmt = 0x00100051;
  cob_trace_statement (STMT_DISPLAY);
  cob_display_field ((cob_field *)&c_22, 32768, "pfb", (cob_field *)&c_23, (cob_field *)&c_6, (cob_field *)&c_7);

  /* Line: 82        : DISPLAY            : number.cob */
#line 82 "number.cob"
  module->statement = STMT_DISPLAY;
#line 237 "number.c"
  module->module_stmt = 0x00100052;
  cob_trace_statement (STMT_DISPLAY);
  cob_display_field (&f_28, 32768, "pfb", (cob_field *)&c_24, (cob_field *)&c_6, (cob_field *)&c_7);

  /* Line: 84        : DISPLAY            : number.cob */
#line 84 "number.cob"
  module->statement = STMT_DISPLAY;
#line 245 "number.c"
  module->module_stmt = 0x00100054;
  cob_trace_statement (STMT_DISPLAY);
  cob_display_field ((cob_field *)&c_25, 32768, "pfb", (cob_field *)&c_26, (cob_field *)&c_27, (cob_field *)&c_7);

  /* Line: 87        : IF                 : number.cob */
#line 87 "number.cob"
  module->statement = STMT_IF;
#line 253 "number.c"
  module->module_stmt = 0x00100057;
  cob_trace_statement (STMT_IF);
  if (((int)cob_cmp_numdisp (b_28, 4, 11LL, 0) > 0))
  {

    /* Line: 89        : MOVE               : number.cob */
#line 89 "number.cob"
    module->statement = STMT_MOVE;
#line 262 "number.c"
    module->module_stmt = 0x00100059;
    cob_trace_statement (STMT_MOVE);
    memset (b_30, 48, 11);

    /* Line: 91        : MOVE               : number.cob */
#line 91 "number.cob"
    module->statement = STMT_MOVE;
#line 270 "number.c"
    module->module_stmt = 0x0010005B;
    cob_trace_statement (STMT_MOVE);
    cob_put_indirect_field (cob_intr_numval (&f_30));
    cob_get_indirect_field (&f_29);
    cob_get_indirect_field (&f_31);

    /* Line: 93        : MOVE               : number.cob */
#line 93 "number.cob"
    module->statement = STMT_MOVE;
#line 280 "number.c"
    module->module_stmt = 0x0010005D;
    cob_trace_statement (STMT_MOVE);
    cob_move (&f_31, &f_30);

    /* Line: 94        : DISPLAY            : number.cob */
#line 94 "number.cob"
    module->statement = STMT_DISPLAY;
#line 288 "number.c"
    module->module_stmt = 0x0010005E;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field (&f_30, 32768, "pfb", (cob_field *)&c_20, (cob_field *)&c_6, (cob_field *)&c_7);

    /* Line: 96        : DISPLAY            : number.cob */
#line 96 "number.cob"
    module->statement = STMT_DISPLAY;
#line 296 "number.c"
    module->module_stmt = 0x00100060;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field ((cob_field *)&c_28, 32768, "pfb", (cob_field *)&c_26, (cob_field *)&c_29, (cob_field *)&c_7);

    /* Line: 97        : DISPLAY            : number.cob */
#line 97 "number.cob"
    module->statement = STMT_DISPLAY;
#line 304 "number.c"
    module->module_stmt = 0x00100061;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field ((cob_field *)&c_30, 32768, "pfb", (cob_field *)&c_31, (cob_field *)&c_29, (cob_field *)&c_32);

    /* Line: 98        : DISPLAY            : number.cob */
#line 98 "number.cob"
    module->statement = STMT_DISPLAY;
#line 312 "number.c"
    module->module_stmt = 0x00100062;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field ((cob_field *)&c_33, 32768, "pfb", (cob_field *)&c_34, (cob_field *)&c_6, (cob_field *)&c_7);

    /* Line: 99        : DISPLAY            : number.cob */
#line 99 "number.cob"
    module->statement = STMT_DISPLAY;
#line 320 "number.c"
    module->module_stmt = 0x00100063;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field (&f_31, 32768, "pfb", (cob_field *)&c_35, (cob_field *)&c_6, (cob_field *)&c_7);

    /* Line: 100       : DISPLAY            : number.cob */
#line 100 "number.cob"
    module->statement = STMT_DISPLAY;
#line 328 "number.c"
    module->module_stmt = 0x00100064;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field ((cob_field *)&c_36, 32768, "pfb", (cob_field *)&c_37, (cob_field *)&c_6, (cob_field *)&c_7);

    /* Line: 101       : DISPLAY            : number.cob */
#line 101 "number.cob"
    module->statement = STMT_DISPLAY;
#line 336 "number.c"
    module->module_stmt = 0x00100065;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field (&f_29, 32768, "pfb", (cob_field *)&c_38, (cob_field *)&c_6, (cob_field *)&c_7);

    /* Line: 102       : DISPLAY            : number.cob */
#line 102 "number.cob"
    module->statement = STMT_DISPLAY;
#line 344 "number.c"
    module->module_stmt = 0x00100066;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field ((cob_field *)&c_39, 32768, "pfb", (cob_field *)&c_40, (cob_field *)&c_6, (cob_field *)&c_7);
  }
  else
  {
    /* ELSE */

    /* Line: 105       : IF                 : number.cob */
#line 105 "number.cob"
    module->statement = STMT_IF;
#line 356 "number.c"
    module->module_stmt = 0x00100069;
    cob_trace_statement (STMT_IF);
    if (((int)cob_cmp_numdisp (b_28, 4, 0LL, 0) != 0))
    {

      /* Line: 107       : DISPLAY            : number.cob */
#line 107 "number.cob"
      module->statement = STMT_DISPLAY;
#line 365 "number.c"
      module->module_stmt = 0x0010006B;
      cob_trace_statement (STMT_DISPLAY);
      cob_display_field ((cob_field *)&c_41, 32768, "pfb", (cob_field *)&c_26, (cob_field *)&c_32, (cob_field *)&c_7);

      /* Line: 108       : DISPLAY            : number.cob */
#line 108 "number.cob"
      module->statement = STMT_DISPLAY;
#line 373 "number.c"
      module->module_stmt = 0x0010006C;
      cob_trace_statement (STMT_DISPLAY);
      cob_display_field ((cob_field *)&c_42, 32768, "pfb", (cob_field *)&c_43, (cob_field *)&c_32, (cob_field *)&c_7);

      /* Line: 109       : DISPLAY            : number.cob */
#line 109 "number.cob"
      module->statement = STMT_DISPLAY;
#line 381 "number.c"
      module->module_stmt = 0x0010006D;
      cob_trace_statement (STMT_DISPLAY);
      cob_display_field (&f_28, 32768, "pfb", (cob_field *)&c_44, (cob_field *)&c_32, (cob_field *)&c_7);
    }
    else
    {
      /* ELSE */

      /* Line: 113       : MOVE               : number.cob */
#line 113 "number.cob"
      module->statement = STMT_MOVE;
#line 393 "number.c"
      module->module_stmt = 0x00100071;
      cob_trace_statement (STMT_MOVE);
      cob_put_indirect_field (cob_intr_numval (&f_30));
      cob_get_indirect_field (&f_29);
      cob_get_indirect_field (&f_31);

      /* Line: 115       : MOVE               : number.cob */
#line 115 "number.cob"
      module->statement = STMT_MOVE;
#line 403 "number.c"
      module->module_stmt = 0x00100073;
      cob_trace_statement (STMT_MOVE);
      cob_move (&f_31, &f_30);

      /* Line: 116       : DISPLAY            : number.cob */
#line 116 "number.cob"
      module->statement = STMT_DISPLAY;
#line 411 "number.c"
      module->module_stmt = 0x00100074;
      cob_trace_statement (STMT_DISPLAY);
      cob_display_field (&f_30, 32768, "pfb", (cob_field *)&c_20, (cob_field *)&c_6, (cob_field *)&c_7);

      /* Line: 118       : DISPLAY            : number.cob */
#line 118 "number.cob"
      module->statement = STMT_DISPLAY;
#line 419 "number.c"
      module->module_stmt = 0x00100076;
      cob_trace_statement (STMT_DISPLAY);
      cob_display_field ((cob_field *)&c_28, 32768, "pfb", (cob_field *)&c_26, (cob_field *)&c_29, (cob_field *)&c_7);

      /* Line: 119       : DISPLAY            : number.cob */
#line 119 "number.cob"
      module->statement = STMT_DISPLAY;
#line 427 "number.c"
      module->module_stmt = 0x00100077;
      cob_trace_statement (STMT_DISPLAY);
      cob_display_field ((cob_field *)&c_33, 32768, "pfb", (cob_field *)&c_34, (cob_field *)&c_6, (cob_field *)&c_7);

      /* Line: 120       : DISPLAY            : number.cob */
#line 120 "number.cob"
      module->statement = STMT_DISPLAY;
#line 435 "number.c"
      module->module_stmt = 0x00100078;
      cob_trace_statement (STMT_DISPLAY);
      cob_display_field (&f_31, 32768, "pfb", (cob_field *)&c_35, (cob_field *)&c_6, (cob_field *)&c_7);

      /* Line: 121       : DISPLAY            : number.cob */
#line 121 "number.cob"
      module->statement = STMT_DISPLAY;
#line 443 "number.c"
      module->module_stmt = 0x00100079;
      cob_trace_statement (STMT_DISPLAY);
      cob_display_field ((cob_field *)&c_36, 32768, "pfb", (cob_field *)&c_37, (cob_field *)&c_6, (cob_field *)&c_7);

      /* Line: 122       : DISPLAY            : number.cob */
#line 122 "number.cob"
      module->statement = STMT_DISPLAY;
#line 451 "number.c"
      module->module_stmt = 0x0010007A;
      cob_trace_statement (STMT_DISPLAY);
      cob_display_field (&f_29, 32768, "pfb", (cob_field *)&c_38, (cob_field *)&c_6, (cob_field *)&c_7);

      /* Line: 123       : DISPLAY            : number.cob */
#line 123 "number.cob"
      module->statement = STMT_DISPLAY;
#line 459 "number.c"
      module->module_stmt = 0x0010007B;
      cob_trace_statement (STMT_DISPLAY);
      cob_display_field ((cob_field *)&c_39, 32768, "pfb", (cob_field *)&c_40, (cob_field *)&c_6, (cob_field *)&c_7);
    }
  }

  /* Line: 128       : GO TO              : number.cob */
#line 128 "number.cob"
  module->statement = STMT_GO_TO;
#line 469 "number.c"
  module->module_stmt = 0x00100080;
  cob_trace_statement (STMT_GO_TO);
  goto l_5;

  /* Line: 130       : Paragraph End-Program             : number.cob */
  l_6:;
#line 130 "number.cob"
  PARAGRAPH_END__PROGRAM_l_6:	module->statement = STMT_ENTRY;
#line 478 "number.c"
  module->module_stmt = 0x00100082;
  module->paragraph_name = st_3;
  cob_trace_para (st_3);

  /* Line: 131       : GOBACK             : number.cob */
#line 131 "number.cob"
  module->statement = STMT_GOBACK;
#line 486 "number.c"
  module->module_stmt = 0x00100083;
  cob_trace_statement (STMT_GOBACK);
  goto exit_program;

  /* Line: 156       : last source line                  :number.cob */
#line 156 "number.cob"
  module->module_stmt = 0x0010009C;
#line 494 "number.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Trace program exit */
  cob_trace_exit (st_1);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  GCACCEPT9_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = &f_27;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field pro */
#line 31 "number.cob"
  cob_nop ();
#line 551 "number.c"
  *(cob_u8_ptr)(b_26) = (unsigned char)'_';

  /* initialize field wKeyPressed */
#line 32 "number.cob"
  cob_nop ();
#line 557 "number.c"
  memset (b_27, (unsigned char)'0', 4);

  /* initialize field wRetCode */
#line 33 "number.cob"
  cob_nop ();
#line 563 "number.c"
  memset (b_28, (unsigned char)'0', 4);

  /* initialize field Field9 */
#line 45 "number.cob"
  cob_nop ();
#line 569 "number.c"
  memset (b_29, (unsigned char)'0', 9);

  /* initialize field FieldX */
#line 46 "number.cob"
  cob_nop ();
#line 575 "number.c"
  memset (b_30, (unsigned char)' ', 11);

  /* initialize field FieldZ */
#line 47 "number.cob"
  cob_nop ();
#line 581 "number.c"
  cob_move (&cob_all_zero, &f_31);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'GCACCEPT9' */

/* Initialize module structure for GCACCEPT9 */
static void GCACCEPT9_module_init (cob_module *module)
{
  module->module_name = "GCACCEPT9";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())GCACCEPT9;
  module->module_cancel.funcptr = (void *(*)())GCACCEPT9_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = ',';
  module->currency_symbol = '$';
  module->numeric_separator = '.';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 6;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

