/* Generated by           cobc 3.2.0 */
/* Generated from         simple.cob */
/* Generated at           set 13 2023 12:16:11 */
/* GnuCOBOL build date    Jul 28 2023 19:10:09 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -g -fsource-location -ftraceall -Q --coverage -A --coverage -v -O0 -x simple.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"simple.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"set 13 2023 12:16:11"
#define  COB_MODULE_DATE		20230913
#define  COB_MODULE_TIME		121611

/* Global variables */
#include "simple.c.h"

/* Function prototypes */

static int		simple ();
static int		simple_ (const int);
static void		simple_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (simple ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'simple' */

/* ENTRY 'simple' */

static int
simple ()
{
  return simple_ (0);
}

static int
simple_ (const int entry)
{
  /* Program local variables */
  #include "simple.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 13        : Entry     simple                  : simple.cob */
  l_2:;
#line 13 "simple.cob"
  ENTRY_SIMPLE:	module->statement = STMT_ENTRY;
#line 105 "simple.c"
  module->module_stmt = 0x0010000D;
  cob_trace_entry (st_1);
  module->section_name = NULL;
  module->paragraph_name = NULL;
  cob_trace_sect (NULL);

  /* Line: 13        : Paragraph 001-INIT                : simple.cob */
#line 13 "simple.cob"
  PARAGRAPH_001__INIT_l_4:	module->statement = STMT_ENTRY;
#line 115 "simple.c"
  module->paragraph_name = st_2;
  cob_trace_para (st_2);

  /* Line: 14        : PERFORM            : simple.cob */
#line 14 "simple.cob"
  module->statement = STMT_PERFORM;
#line 122 "simple.c"
  module->module_stmt = 0x0010000E;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM 002-SHOW */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 6;
  frame_ptr->return_address_ptr = &&l_7;
  goto l_6;
  l_7:
  frame_ptr--;

  /* Line: 15        : ACCEPT             : simple.cob */
#line 15 "simple.cob"
  module->statement = STMT_ACCEPT;
#line 138 "simple.c"
  module->module_stmt = 0x0010000F;
  cob_trace_statement (STMT_ACCEPT);
  cob_accept (&f_18);

  /* Line: 16        : DISPLAY            : simple.cob */
#line 16 "simple.cob"
  module->statement = STMT_DISPLAY;
#line 146 "simple.c"
  module->module_stmt = 0x00100010;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &c_1);

  /* Line: 17        : Paragraph 001-END-PRG             : simple.cob */
#line 17 "simple.cob"
  PARAGRAPH_001__END__PRG_l_5:	module->statement = STMT_ENTRY;
#line 154 "simple.c"
  module->module_stmt = 0x00100011;
  module->paragraph_name = st_3;
  cob_trace_para (st_3);

  /* Line: 18        : STOP RUN           : simple.cob */
#line 18 "simple.cob"
  module->statement = STMT_STOP_RUN;
#line 162 "simple.c"
  module->module_stmt = 0x00100012;
  cob_trace_statement (STMT_STOP_RUN);
  cob_stop_run (b_2);

  /* Line: 19        : Paragraph 002-SHOW                : simple.cob */
  l_6:;
#line 19 "simple.cob"
  PARAGRAPH_002__SHOW_l_6:	module->statement = STMT_ENTRY;
#line 171 "simple.c"
  module->module_stmt = 0x00100013;
  module->paragraph_name = st_4;
  cob_trace_para (st_4);

  /* Line: 20        : DISPLAY            : simple.cob */
#line 20 "simple.cob"
  module->statement = STMT_DISPLAY;
#line 179 "simple.c"
  module->module_stmt = 0x00100014;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &c_2);

  /* Line: 21        : MOVE               : simple.cob */
#line 21 "simple.cob"
  module->statement = STMT_MOVE;
#line 187 "simple.c"
  module->module_stmt = 0x00100015;
  cob_trace_statement (STMT_MOVE);
  memcpy (b_17, "0001", 4);

  /* Line: 22        : MOVE               : simple.cob */
#line 22 "simple.cob"
  module->statement = STMT_MOVE;
#line 195 "simple.c"
  module->module_stmt = 0x00100016;
  cob_trace_statement (STMT_MOVE);
  cob_move ((cob_field *)&c_3, COB_SET_FLD (f0, 20, b_19, &a_1));

  /* Line: 23        : DISPLAY            : simple.cob */
#line 23 "simple.cob"
  module->statement = STMT_DISPLAY;
#line 203 "simple.c"
  module->module_stmt = 0x00100017;
  cob_trace_statement (STMT_DISPLAY);
  cob_display (0, 1, 1, &f_17);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 24        : last source line                  :simple.cob */
#line 24 "simple.cob"
  module->module_stmt = 0x00100018;
#line 215 "simple.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Trace program exit */
  cob_trace_exit (st_1);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  simple_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field ONE */
#line 6 "simple.cob"
  cob_nop ();
#line 272 "simple.c"
  memset (b_17, 48, 4);

  /* initialize field wk-key */
#line 7 "simple.cob"
  cob_nop ();
#line 278 "simple.c"
  *(cob_u8_ptr)(b_18) = (unsigned char)' ';

  /* initialize field PARM */
#line 8 "simple.cob"
  cob_nop ();
#line 284 "simple.c"
  memset (b_19, (unsigned char)' ', 400);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'simple' */

/* Initialize module structure for simple */
static void simple_module_init (cob_module *module)
{
  module->module_name = "simple";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())simple;
  module->module_cancel.funcptr = (void *(*)())simple_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 6;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

