/* Generated by           cobc 3.2.0 */
/* Generated from         simple.cob */
/* Generated at           set 13 2023 12:16:11 */
/* GnuCOBOL build date    Jul 28 2023 19:10:09 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -g -fsource-location -ftraceall -Q --coverage -A --coverage -v -O0 -x simple.cob */

/* Program local variables for 'simple' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_17[4] __attribute__((aligned));	/* ONE */
static cob_u8_t	b_18[1] __attribute__((aligned));	/* wk-key */
static cob_u8_t	b_19[400] __attribute__((aligned));	/* PARM */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17	= {4, b_17, &a_3};	/* ONE */
static cob_field f_18	= {1, b_18, &a_1};	/* wk-key */

/* End of fields */

