/* Generated by           cobc 3.2.0 */
/* Generated from         simple.cob */
/* Generated at           set 13 2023 12:16:11 */
/* GnuCOBOL build date    Jul 28 2023 19:10:09 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -g -fsource-location -ftraceall -Q --coverage -A --coverage -v -O0 -x simple.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_3 =	{0x10,   4,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {7, (cob_u8_ptr)"THE END", &a_2};
static const cob_field c_2	= {26, (cob_u8_ptr)"Demonstration of step over", &a_2};
static const cob_field c_3	= {4, (cob_u8_ptr)"TEST", &a_2};


/* Strings */
static const char st_1[]	= "simple";
static const char st_2[]	= "001-INIT";
static const char st_3[]	= "001-END-PRG";
static const char st_4[]	= "002-SHOW";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"simple.cob"};

#define cob_nop	if (!module) cob_nop

